### ISSUE TITLE
Install failure. Windows 10

### ISSUE THREAD

**Issue by cozzbie** [tojocky/node-printer#102]
Get the following error when I try to npm this on a windows machine.

> printer@0.2.1 install A:\proj\scholastica\node_modules\printer
> node-gyp rebuild

>A:\proj\scholastica\node_modules\printer>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\
.js" rebuild )  else (node  rebuild )
>gyp ERR! configure error
>gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
>gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
>gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:119:14)
>gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:108:9
>gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
>gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
>gyp ERR! stack     at maybeClose (child_process.js:1015:16)
>gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
>gyp ERR! stack     at Socket.emit (events.js:107:17)
>gyp ERR! stack     at Pipe.close (net.js:485:12)
>gyp ERR! System Windows_NT 6.3.9600
>gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
>gyp ERR! cwd A:\proj\scholastica\node_modules\printer
>gyp ERR! node -v v0.12.7
>gyp ERR! node-gyp -v v2.0.1
>gyp ERR! not ok
>npm ERR! Windows_NT 6.3.9600
>npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "printer" "--save"
>npm ERR! node v0.12.7
>npm ERR! npm  v2.11.3
>npm ERR! code ELIFECYCLE

>npm ERR! printer@0.2.1 install: `node-gyp rebuild`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the printer@0.2.1 install script 'node-gyp rebuild'.
>npm ERR! This is most likely a problem with the printer package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     node-gyp rebuild
>npm ERR! You can get their info via:
>npm ERR!     npm owner ls printer
>npm ERR! There is likely additional logging output above.

Any help is highly appreciated.

**Comment by cozzbie** [comment]
Also i must add. I recently updated my node install

**Comment by tojocky** [comment]
Use Python 2 by default. Not 3

**Comment by cozzbie** [comment]
Used that already. Finally got it working by using instructions from the node-gyp github page. But now something interesting is happening, when I try

npm install printer

I get the repository at

https://github.com/alepee/node-printer

and not yours which is at

https://github.com/tojocky/node-printer

Is there something I might be doing wrong?

**Comment by cozzbie** [comment]
Just found out it downloaded both repos. WOW. Thanks. Will close
