### ISSUE TITLE
Pre-compiled binary for WIndows and Linux ?

### ISSUE THREAD

**Issue by mdennyh** [tojocky/node-printer#104]
I really love this project, and I use it a lot, but It bothers me that I have to install Visual Studio, python and  set environment PATH just to make this works. It'll be nice to have node-printer binary pre-compiled for windows or linux, doesn't it ?

**Comment by xiongsongsong** [comment]
I really hope to provide pre-compiled version.
Because I tested many times in a virtual machine, or compile unsuccessful, too much trouble.

<img width="915" alt="screen shot 2016-05-24 at 8 50 27 am" src="https://cloud.githubusercontent.com/assets/342509/15488802/b31eeb20-218c-11e6-9729-b931c591e47f.png">

**Comment by tojocky** [comment]
Do you prefer yo have a npm package with precompiled binaries or separate package for each OS/arch?
On top it depends on node.js version.

I started this https://github.com/tojocky/node-printer-bin but I used only for one specific project.
It would be great for npm install to have mechanism to copy specific files based on node.js version, os and architecture.

**Comment by vasumahesh1** [comment]
Hi @tojocky 
I created binaries for node-printer yesterday. I am using [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp) to generate tars for the module and upload them to S3.

Tried the npm install and it worked by pulling the archived tar from S3.

The question is, how should I go about making the changes for the PR?

**Comment by xiongsongsong** [comment]
thanks!

Compile different versions and upload it to S3 is a good choice, the system automatically determines when npm install and download the corresponding version.Feasible?

**Comment by tojocky** [comment]
https://github.com/tojocky/node-printer/issues/70
