### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by goodseller** [tojocky/node-printer#105]
Thanks for sharing this nice module.

As I am trying the example, I found something seems like typo issue in `node-printer/examples/printFile.js` or is it?

Should the line 10 and 22 (the same) be the follow:

Current:
```
 printer: process.env[3], // printer name, if missing then will print to default printer
```

Should be ?_?
```
 printer: process.argv[3], // printer name, if missing then will print to default printer
```

**Comment by kamaldeepoodles** [comment]
Hey tojockey, can you please provide me your skype ID. Need to discuss something.

**Comment by tojocky** [comment]
Ion_lupascu

**Comment by kamaldeepoodles** [comment]
please accept request from kamaldeep.oodles
