### ISSUE TITLE
error when using with electron

### ISSUE THREAD

**Issue by cinder92** [tojocky/node-printer#107]
Hello, thanks for this module

i have installed this module with npm to my project builded in electron, but when i want to require("printer"), the following message come out 

![captura de pantalla 2016-01-15 a las 7 04 36 p m](https://cloud.githubusercontent.com/assets/4725556/12368570/96c8e6fc-bbba-11e5-811e-7cded7632b8c.png)

i'm using this line of code 

var printer = require("printer"),
      util = require('util');
    console.log("installed printers:\n"+util.inspect(printer.getPrinters(), {colors:true, depth:10}));

Thanks a lot!

**Comment by vasumahesh1** [comment]
Weird. I am using node-printer with electron. Did you do [electron-rebuild](https://github.com/electronjs/electron-rebuild) ? I had an issue while using this and after using electron-rebuild it worked like a charm.

**Comment by cinder92** [comment]
yes i'm but is not working, is showing the following message

Unable to find electron-prebuilt's version number, either install it or specify an explicit version

**Comment by vasumahesh1** [comment]
When you did electron-rebuild you got that error? you have to have electron-prebuilt in the same folder as electron-rebuild for the rebuild to work correctly.

**Comment by cinder92** [comment]
yes i'm in the same folder that my project is, but when im execute this code, still crashing

./node_modules/.bin/electron-rebuild -v 0.34.3 -e /usr/local/lib/node_modules/electron-prebuilt

**Comment by cinder92** [comment]
it's working now! version of my electron is 0.36.3, thanks  a lot!

**Comment by antoinepairet** [comment]
@cinder92 Good to know it works for you. Please close the issue.
Regards
