### ISSUE TITLE
issue in following the steps

### ISSUE THREAD

**Issue by jawahar5** [tojocky/node-printer#110]
Hi Team,

I get the error during the operation "nw-gyp rebuild". I have tried this in Ubuntu 32 bit system. I have also used sudo apt-get install libcups2-dev. But i got the following error. Please help.
Thank you.

gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@4.1.2 | linux | ia32
gyp http GET http://node-webkit.s3.amazonaws.com/v4.1.2/nw-headers-v4.1.2.tar.gz
gyp http 404 http://node-webkit.s3.amazonaws.com/v4.1.2/nw-headers-v4.1.2.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack at Request.<anonymous> (/usr/local/lib/node_modules/nw-gyp/lib/install.js:236:14)
gyp ERR! stack at emitOne (events.js:82:20)
gyp ERR! stack at Request.emit (events.js:169:7)
gyp ERR! stack at Request.onRequestResponse (/usr/local/lib/node_modules/nw-gyp/node_modules/request/request.js:952:10)
gyp ERR! stack at emitOne (events.js:77:13)
gyp ERR! stack at ClientRequest.emit (events.js:169:7)
gyp ERR! stack at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack at emitOne (events.js:77:13)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/nw-gyp" "rebuild"
gyp ERR! cwd /home/sathish/NewPrinterOne/node_modules/printer
gyp ERR! node -v v4.1.2
gyp ERR! nw-gyp -v v0.13.0
gyp ERR! not ok

**Comment by tojocky** [comment]
use correct build parameters.
