### ISSUE TITLE
Print job goes to printer, printer data light blinks, nothing printed

### ISSUE THREAD

**Issue by brandonros** [tojocky/node-printer#114]
Tell me how to enable logging so I can give more information.

One printer on Windows printed a PDF no problem (Brother).

However, my Zebra won't.

Windows 7, node 5.1.0

**Comment by tojocky** [comment]
I doubt that Zebra can print PDF file. Check the spec.
As far as I know, Zebra recognise RAW commands

**Comment by brandonros** [comment]
What would you recommend as protocol to convert the PDF?

The driver on Windows +  Mac allows printing PDF files. Not sure what kind of conversion goes on in the background.

**Comment by brandonros** [comment]
Also, on Mac, a Zebra ZP505 prints a PDF no problem.

**Comment by brandonros** [comment]
Here is a little bit for the Googlers of the world. I should probably add some SEO efficient keywords while I'm at it. :p

Imagemagick will not work. You can not convert to EMF, only read it in.
Ghostscript will not work. gsprint and the `-sDEVICE=mswinpr2 -sOutputFile=%printer%printer name` both crash on both win32 + win64.
spool (http://www.compuphase.com/software_spool.htm) achieves the same that this wonderful plugin does: pass the file, let it fail because the printer doesn't accept PDF.

node-pdfium-native (@tojocky) doesn't compile either.

So, I've pretty much tried everything -_-

**Comment by rkaw92** [comment]
If it's any help at this point, we talk to a Zebra via raw TCP and send ZPLs to it on port 9100 in production.
I *think* we've tested PDF printing using printDirect with { type: 'RAW' } and some magic strings before and after the PDF itself (looking at the code right now), but I do not have a live printer to check at the moment.
