### ISSUE TITLE
error of use printer.printDirect

### ISSUE THREAD

**Issue by jin-pan** [tojocky/node-printer#116]
i build the module with nw.js 0.12.3 (winXP-32) use nw-gyp0.13.0 and node.js 5.4.1.
my test code is :

`var printer = require("node_printer");

console.log('default printer name: ' + (printer.getDefaultPrinterName() || 'is not defined on your computer'));

```
printer.printDirect({
    data:"some text" // or simple String: "some text"

//  , printer:'PDFCreator' // printer name, if missing then will print to default printer

    , type: 'RAW' // type: RAW, TEXT, PDF, JPEG, .. depends on platform

    , success:function(jobID){console.log("sent to printer with ID: "+jobID);}
    , error:function(err){console.log(err);}
});`
```

the "printer.getDefaultPrinterName()" can return the printer name of "PDFCreator".
but it catch error when "printer.printDirect".
the error show in cosole is:
 "
Uncaught TypeError: Expected 5 arguments
(anonymous function)
"

what's wrong of it??

**Comment by tojocky** [comment]
Use type: "TEXT"

**Comment by jin-pan** [comment]
I use every options of the type for test,The error still occur.
and I use node.js 4.3.0 to rebuild the module, It is not useful too.

and i use another pdf pinter:

my test code is:
=========================================================
=========================================================
var printer = require("node_printer"),
    util = require('util');
console.log("supported formats are:\n"+util.inspect(printer.getSupportedPrintFormats(), {colors:true, depth:10}));
console.log('default printer name: ' + (printer.getDefaultPrinterName() || 'is not defined on your computer'));
printer.printDirect({data:"print from Node.JS buffer" // or simple String: "some text"
	//, printer:'Foxit Reader PDF Printer' // printer name, if missing then will print to default printer
	, type: 'TEXT' // type: RAW, TEXT, PDF, JPEG, .. depends on platform
	, success:function(jobID){
		console.log("sent to printer with ID: "+jobID);
	}
	, error:function(err){console.log(err);}
});

=========================================================
=========================================================
the console show:
supported formats are:
[ [32m'RAW'[39m,
  [32m'XPS_PASS'[39m,
  [32m'RAW'[39m,
  [32m'NT EMF 1.006'[39m,
  [32m'NT EMF 1.007'[39m,
  [32m'NT EMF 1.008'[39m,
  [32m'TEXT'[39m,
  [32m'RAW'[39m,
  [32m'RAW [FF appended]'[39m,
  [32m'RAW [FF auto]'[39m,
  [32m'NT EMF 1.003'[39m,
  [32m'NT EMF 1.006'[39m,
  [32m'NT EMF 1.007'[39m,
  [32m'NT EMF 1.008'[39m,
  [32m'TEXT'[39m ]

default printer name: Adobe PDF
Uncaught TypeError: Expected 5 arguments
(anonymous function)

Help!!!

**Comment by jin-pan** [comment]
Hi,tojocky:

if i use this:

printer.printDirect(1,1,1,1,1,1,1);

the error catch is:
Uncaught TypeError: Argument 0 must be a string or Buffer

so i think the error is on arguments passing and receiving.

Please help to give same advise about the error.

**Comment by tojocky** [comment]
Strange, only you have this issue.
You can try to remove this line:
https://github.com/tojocky/node-printer/blob/master/src/node_printer_win.cc#L669

Recompile and let me know what do you have.

**Comment by berolak-shaman** [comment]
I use nwjs 0.14.7 and catch error "Argument 1 must be a string". I rebuild module with nw-gyp.

**Comment by jin-pan** [comment]
oh! one year is pass!
few days ago,when i view this project and find it had some update.
So,I try it again.
long time is pass and my Win xp is remake again.
and i build this printer with Win xp sp3/ vs2010/node5.12.0.
finally,the job is done.

thank you tojocky. you are a good gay!

**Comment by 1dal** [comment]
same problem here.

**Comment by JeffJassky** [comment]
Setting my default printer fixed this for me.
