### ISSUE TITLE
Uncaught Error: %1 is not a valid win32 application

### ISSUE THREAD

**Issue by pabatribick** [tojocky/node-printer#118]
I've testet it on Ubuntu and it works perfectly. But after i tested it on Windows 7 and 8, it would fail to Output the Printerlist with following Error in the DevTools-Console: Uncaught error 1 is not a valid win32 application *\resources\app\node_modules\printer\build\Release\node_printer.node

Am i the only one that does have this problem?

**Comment by tojocky** [comment]
did you compile correct? Be careful if you have x64 CPU/OS architecture, but you node.js is x32

**Comment by pabatribick** [comment]
Thanks for your Answer.

But i can compile from Linux 64bit to Windows or OS X, is that correct? And how i find out which bit version of node.js is installed?

**Comment by tojocky** [comment]
node --version
