### ISSUE TITLE
Paper cut not working after  barcode

### ISSUE THREAD

**Issue by bgobi1991** [tojocky/node-printer#119]
Hi Team,
After bar code, the paper cut is not working ,
\x1b\x45\x01 - text bold
\x1d\x68\50 - bar code height
\x1d\x6b\x02 - bar code EAN13
\x0a - line feed
\x1d\x56\x00 - paper cut 

var printData = " Ack. Y297026163 \n\r Pos ID: 2020030072 \n\r \x1b\x45\x01 YANTRA GROUP-NV  \n\r \x1d\x68\50 \x1d\x6b\x02 123456789012 \x0a  \x1d\x56\x00";

    printer.printDirect({
        data: printData
        , printer: postData.pname
        , type: 'RAW'
        , success:function(jobID){
            res.end(JSON.stringify({"msg": "Test print successfully"}));
        }
        , error:function(err){res.end(JSON.stringify({"msg": "Failed to print"}));}
    });

Kindly give the feedback.

**Comment by tojocky** [comment]
This is expected because you have to use [Buffer](https://nodejs.org/api/buffer.html) type instead of text. The issue is that JavaScript text is UTF8, but printer understand ASCII/byte code.

**Comment by tojocky** [comment]
same as #25
