### ISSUE TITLE
It is not compatible with node 5.9 ? SO = Windows 32 bits

### ISSUE THREAD

**Issue by glauberalmeida** [tojocky/node-printer#122]
Please, step by step installation for windows 32 bits and node 5.9!

**Comment by antoinepairet** [comment]
Hi, 
I made a PR #123 to test against node 4.4 and 5.9. If the builds succeed, you probably have a configuration issue on your machine. If they do not, the library might require some changes (use NAN 2 ?)

rgds

**Comment by tojocky** [comment]
Hi, I think the issue is on your side. I updated appveyor with the latest node.js version and looks good: https://ci.appveyor.com/project/tojocky/node-printer/build/45

I don't have any windows 32 bits, but feel free to add more info of your issue.
