### ISSUE TITLE
Uncaught Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by feedm3** [tojocky/node-printer#125]
Hi guys,
I'm having problems getting the node-printer module to run on windows. When I start electron I get the error message  `Uncaught Error: A dynamic link library (DLL) initialization routine failed.`

What I did:
1. installed VS 2013
2. installed Phython 2.7.10
3. run `npm install -g node-gyp`
4. run `npm install printer --save --msvs_version=2013`
5. required the module in my script
6. started electron

Did I miss something?

**Comment by vasumahesh1** [comment]
[electron-rebuild](https://github.com/electronjs/electron-rebuild) missed

**Comment by feedm3** [comment]
Thanks for the quick reply! I installed the package and run `.\node_modules\.bin\electron-rebuild.cmd` but when I then start my app the error is still there :(

**Comment by feedm3** [comment]
Theres an open issue on the electron-rebuild package which seems to be relevant for my problem https://github.com/electron/electron-rebuild/issues/53.

Are there any other ways to rebuild the app?

**Comment by feedm3** [comment]
Ok, I got it to work. I had to rebuild it with `node-gyp`. Feels a little nasty.

```
cd node_modules\printer
node-gyp rebuild --target=0.37.4 --arch=x64 --dist-url=https://atom.io/download/atom-shell
``` 

Shouldn't this get mentioned in the readme?

**Comment by vasumahesh1** [comment]
Weird. It works for me without any params. I have Windows 8.1 VS2013.

**Comment by vasumahesh1** [comment]
Weird Electron Rebuild worked for me...

**Comment by tojocky** [comment]
Thanks.
I added in README.

**Comment by jzatarain** [comment]
The electron-rebuilt thing should be in the readme, IMO. This helped me after two days of trying to work this out.

**Comment by jzatarain** [comment]
I had to do this:

If visual studio 2015 is installed, uninstall it

npm install --global --production windows-build-tools
npm config set msvs_version 2015
npm install printer --msvs_version=2015 --build-from-source=node_printer --target_arch=x64
npm install electron-rebuild
.\node_modules\.bin\electron-rebuild.cmd

Now you can run electron and the printer module should work.
