### ISSUE TITLE
error on printing: TypeError: StartDocPrinterW error: code: 1804, message: ָ��������������Ч��

### ISSUE THREAD

**Issue by randianb** [tojocky/node-printer#128]
var pdfoptions = {
                    data: fs.readFileSync('D:/11/22.pdf'),
                    outputFormat: 'EMF' // could be a item from pdfium.getSupportedOutputFormats();
                }; 
                pdfium.render(pdfoptions, function(err, data) {
                    if(err) {
                        return console.error('error from async convert: ', err);
                    } 
                     printPages(data);
                });
                function printPages(iPages) {
                    if(!iPages) {
                        return console.error('no pages');
                    } 
                    var i;
                    for(i = 0; i < iPages.length; ++i) {
                        data = iPages[i];
                        if(data instanceof Buffer) { 
                            pdfprint(data);
                        }
                    }
                }
                function pdfprint(data){
                     printer.printDirect({
                        printer:vm.myprinters,
                        data: data, 
                        type: 'EMF',
                        docname:'test',
                        success: function(id) {
                            console.log('printed with id ' + id);
                        },
                        error: function(err) {
                            console.error('error on printing: ' + err);
                        }
                    });
                }

**Comment by randianb** [comment]
the same to "type:'PDF'"

**Comment by tojocky** [comment]
The pdfium package is not finished yet. Feel free to contribute. Unfortunately I don't have time to finish.
