### ISSUE TITLE
Uncaught Error: Cannot find module "."

### ISSUE THREAD

**Issue by boatrite** [tojocky/node-printer#130]
NPM version 2.15.1
Node version 4.4.3
Using electron 1.1.0
Using Ubuntu 14.04 (libcups2-dev is installed)

I get `Uncaught Error: Cannot find module "."` when trying to `require("printer")`. The error gets thrown from `printer.js` line 12: `printer_helper = require('./node_printer_'+process.platform+'_'+process.arch+'.node');`

If I set a breakpoint there and evaluate that line in the console, I get `Uncaught Error: Cannot find module './node_printer_linux_x64.node'`.

The weird thing is, if I set a breakpoint on the `require("printer");` line, in the console, I can do `require("printer");` and it totally works.

This may or may not be related, but when I `let printer = require("printer");` in one of my files, Webpack complains saying:

```
WARNING in ./~/printer/lib/printer.js
Critical dependencies:
10:21-45 the request of a dependency is an expression
 @ ./~/printer/lib/printer.js 10:21-45
```

Appreciate any help. Cheers.

**Comment by tojocky** [comment]
try to build the package.

**Comment by boatrite** [comment]
How do I do that? This is what I attempted as per https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

First I tried

```
$ cd /node_modules/printer
$ HOME=~/.electron-gyp node-gyp rebuild --target=1.1.0 --arch=x64 --dist-url=https://atom.io/download/atom-shell
```

That didn't change anything, so I did

```
export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_target=1.1.0
export npm_config_arch=x64
export npm_config_runtime=electron
HOME=~/.electron-gyp npm install printer
```

which also didn't change fix the error. Then I did

```
npm install --save-dev electron-rebuild
./node_modules/.bin/electron-rebuild
```

which also didn't do anything.

The weird thing is, `node_modules/printer/build/Release/node_printer.node` does exist. But for some reason it's not being required correctly.

**Comment by danielecr** [comment]
> The weird thing is, node_modules/printer/build/Release/node_printer.node does exist. But for some reason it's not being required correctly.
exactly, I have the same problem with electron
It looks like the path resolver is broken when run in electron

does process.platform and process.arch have the same values in electron? those should

**Comment by danielecr** [comment]
I added some console.log() in printer.js and I found that it works only from the main process, not from the renderer process. So this way:

```
const electron = require('electron')
var printer = electron.remote.require('printer')
printer.getPrinters().forEach( (aPrinter) => {
   console.log('aPrinter',aPrinter);
})
```
from render process works as expected (log the available printer list on renderer's console)
