### ISSUE TITLE
node-printer to print the supermarket receipts: content for the LOGO pictures and the information such as order number, serial number, payment time. How to print the LOGO pictures?

### ISSUE THREAD

**Issue by endeavorChineseBoy** [tojocky/node-printer#134]
Is now printed below the text, but the LOGO above pictures don't know how to print, how to print the picture LOGO? thank you.
var str = ''+
	'------------------------------\n'+
	'门店:叶氏兄弟\n'+
	'订单号:165789635456\n'+
	'流水号:165461561351515616516156\n'+
	'收银员:zqq\n'+
	'日期时间:2014-1-2 12:32\n'+
	'应付款:323元\n'+
	'已付款:234元\n' +
	'------------------------------'+
	'\n\n\n\n\n\n';
printer.printDirect(
{
	data:iconv.convert(str) // // printer name
	, type: 'RAW' // type: RAW, TEXT, PDF, JPEG, .. depends on platform
	, success:function(jobID){
	console.log("sent to printer with ID: "+jobID);
	}
	, error:function(err){console.log(err);}
	}
);

**Comment by endeavorChineseBoy** [comment]
Chinese paper

**Comment by tojocky** [comment]
Check printer driver manual. node-printer allow you to send a list of bytes (Boffer) containing printer commands and data (text, image, etc...).
