### ISSUE TITLE
getJob() error when the print job finished.

### ISSUE THREAD

**Issue by XiaohuChen** [tojocky/node-printer#136]
I'm using Node-Webkit to print documents on windows, and I use setInteval() to check how many pages has been printed periodically, I can use getJob() to get the job infomation through jobID, but when the job finished, getJob() thow an error on the console like this:

Uncaught TypeError: Error on GetJob. Wrong job id or it was deleted: code: 87, message:����������. 

 So, how to get the infomation when the job  finished?

**Comment by XiaohuChen** [comment]
And does anyone know how to use node-webkit to print docx/doc files on windows ?

**Comment by tojocky** [comment]
`getPrinter(printerName)` should return pending jobs as well.
