### ISSUE TITLE
how do use esc/pos command print??

### ISSUE THREAD

**Issue by c941010623** [tojocky/node-printer#14]
ex: ESC @ 

ESC @ 
Name Initialize printer 
Code ASCII ESC @ 
 Hex. 1B 40 
 Decimal 27 64 
Function Clears data from the print buffer and sets the printer to its default settings. 
Details ï DIP switch settings are not reload. 
 ï Data in the reception buffer is maintained. 
 ï Macro definition information is maintained. 
 ï NV bit image definition information is maintained. 
 ï User NV memory data is maintained. 
 ï When page mode is selected, this recovers to standard mode. 
STAR The printer is initialized by this command under the following conditions. 
 ï Selection of an effective paper out detector for paper out signal output (ESC c 3n) 
 ï Select an effective paper out detector for printing stop (ESC c 4n) 

buffer write \x1B\x40 ??

**Comment by AlexZhouAA** [comment]
@c941010623 I am facing the similar problem. The only difference is I'm using Simplified Chinese Characters. They're all garbled after printed.
Please help, if you solved it.
Thanks a lot.
