### ISSUE TITLE
Print job shows up in queue then quickly disappears

### ISSUE THREAD

**Issue by pfjare** [tojocky/node-printer#141]
I can send a job to the printer but the print job quickly disappears. I can successfully print only when using `TEXT` type.

I am on Windows 10.

Example code:

```
printer.printDirect({data: fs.readFileSync('testsvg.emf')
    , printer:'Canon MX920 series Printer'
    , type: 'NT EMF 1.006'
    , success:function(jobID){
        console.log("sent to printer with ID: "+jobID);
    }
    , error:function(err){console.log(err);}
});

```

**Comment by igorcandeia** [comment]
Same error here

**Comment by nikhilwadibhasme** [comment]
I also get the same behaviour. I could see the document in the printer queue but not getting print.
When i tried with 'Microsoft Print To PDF' its not creating the pdf as well.

**Comment by happilymarrieddad** [comment]
Same thing for me.

**Comment by nikhilwadibhasme** [comment]
@happilymarrieddad  hey use electron-edge-printer. I made it for printer functionality for electron.

**Comment by happilymarrieddad** [comment]
thanks man!

**Comment by julienazerty** [comment]
Hi,
@nikhilwadibhasme I'm facing the same issue, but not sure to understand what is electron and if i need it because i'm on an API so no browser involved. Any idea/advice ?

**Comment by happilymarrieddad** [comment]
For anyone still trying to use this, I send my print documents to foxit reader and they print automatically. No need to even setup the printer. I've been doing this with node and it works great!!!

**Comment by nikhilwadibhasme** [comment]
@happilymarrieddad  is that not working for other printers?

**Comment by nikhilwadibhasme** [comment]
@julienazerty  read https://electron.atom.io/ for electron info. This will allow u to create desktop app using node js. then Try using electron-edge-printer for printing and fetching/setting printer settings in the printing. Let me know if u face any issue.

**Comment by julienazerty** [comment]
@nikhilwadibhasme Ok i'll try this. Thanks

**Comment by julienazerty** [comment]
I'm unable to install electron-edge-printer. 
Error : Cannot read property 'InitializeClrFunc' of undefined. Do have i to install other module before installing electron-edge-printer ?

**Comment by nikhilwadibhasme** [comment]
@julienazerty  yes check if all dependencies are installed properly (electron,electron-edge etc).

**Comment by julienazerty** [comment]
@nikhilwadibhasme. I'm trying to install electron but still no luck : 
Error : Tunneling socket could not be established, cause=connect ETIMEOUT 222.192.20.150

Ps: I'm behind an enterprise proxy but with npm configured to go through. I don't have any issue on downloading other package from npm.    
 
222.192.20.150 is still alive ? Do you get this result too ?

**Comment by julienazerty** [comment]
@nikhilwadibhasme Ok i tried again but from another network then installation worked. So the last errors connect TIMEOUT was an issue from my company's proxy. (Step by step '^^) 
Tomorrow i'll be able to test printing and let you know. 
Thanks for your help :)

**Comment by nikhilwadibhasme** [comment]
@julienazerty yes please let me know for any issue. i will be pushing latest fine version of that module to git shortly. please let me know what else printer properties you will need , till now orientation,page size,page tray, number of copies, duplex and output color is supported.

**Comment by julienazerty** [comment]
@nikhilwadibhasme electron, electron-edge and electron-edge-printer are installed. And also Expressjs for the Http request handling. 
But if i add var edgeprinter = require('electron-edge-printer') i've got an error  :
TypeError : Cannot read property 'initializeClrFunc' of undefined 
at node_modules/electron-edge/lib/edge.js : 169

**Comment by nikhilwadibhasme** [comment]
@julienazerty  check the angular example in that repo. It should help.

**Comment by vadhack** [comment]
Hi, is there any way to solve this problem without using electron? I have tested this library in linux and it works correctly but in windows 10 it does not print, it sends the print command correctly but does not print anything. 

Please i need help.

**Comment by with-shrey** [comment]
@vadhack Were you able to solve it ?
