### ISSUE TITLE
Electron Build Howto

### ISSUE THREAD

**Issue by chrishemmings** [tojocky/node-printer#144]
Can we get some additional documentation on how to get this module working with Electron.  For the life of me, I can get this thing to work at the moment.

Thanks!

**Comment by tojocky** [comment]
Hi, I think it should be easy... you just need to figure out what exact node.js version is used, build with a specific version.
A more detailed instruction you can find here: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by mpaleo** [comment]
@tojocky Hi ! Can you provide a step by step of node-printer + electron ? 
Thanks a lot
