### ISSUE TITLE
Electron + windows build trouble

### ISSUE THREAD

**Issue by yomansk8** [tojocky/node-printer#148]
I'm trying to use this module in an Electron application (version 1.4.5) built on Windows 10 but it wont work.
When I'm running my project, I caught the following error : 
_Uncaught Error: Cannot find module "."_

When I check the printer.js file to see where is the problem, it seems that it failed to require the node_printer.node file.

The file is correctly built in the releases folder.

I cant find what is the problem.

**Comment by tojocky** [comment]
Try to rebuild it

**Comment by yomansk8** [comment]
I've already tried to rebuilt it a couple of time. No success...

I tried with : 
`npm install --save printer --msvs_version=2015`
and
`npm install --save node-printer --runtime=electron --target=1.4.5 --target_arch=x64r`
`npm install --save printer --msvs_version=2015  --build-from-source=node_printer`

Am I doing it right ?

**Comment by yomansk8** [comment]
I've also tried rebuild like this : 
`node-gyp rebuild --target=1.4.5 --arch=x64 --dist-url=https://atom.io/download/atom-shell`

No change.

**Comment by vasumahesh1** [comment]
The electron prebuilt hasn't been published yet (so the last two wont work). So I tried a regular build:

`build/Releases/node_printer.node` should exist. is it there?

Just did a build here is my log:
```
PS P:\Node\test> npm install printer

> printer@0.2.2 install P:\Node\test\node_modules\printer
> node-gyp rebuild


P:\Node\test\node_modules\printer>if not defined npm_config_node_gyp (node "C:\Users\vasum\AppData\Roaming\nvm\v6.9.1\no
de_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  node_printer.cc
  node_printer_win.cc
  win_delay_load_hook.cc
     Creating library P:\Node\test\node_modules\printer\build\Release\node_printer.lib and object P:\Node\test\node_mod
  ules\printer\build\Release\node_printer.exp
  Generating code
  Finished generating code
  node_printer.vcxproj -> P:\Node\test\node_modules\printer\build\Release\\node_printer.node
  node_printer.vcxproj -> P:\Node\test\node_modules\printer\build\Release\node_printer.pdb (Full PDB)
P:\Node\test
`-- printer@0.2.2

npm WARN enoent ENOENT: no such file or directory, open 'P:\Node\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
PS P:\Node\test> node .\printer.js
[ { name: 'Send To OneNote 2013',
    portName: 'nul:',
    driverName: 'Send to Microsoft OneNote 15 Driver',
    printProcessor: 'winprint',
    datatype: 'RAW',
    status: [],
    statusNumber: 0,
    attributes: [ 'DO-COMPLETE-FIRST', 'LOCAL' ],
    priority: 1,
    defaultPriority: 0,
    averagePPM: 0 },
```

**Comment by yomansk8** [comment]
Yes, the file is in the right place.

![image](https://cloud.githubusercontent.com/assets/1978745/20010567/d3e4c210-a2a8-11e6-835d-0d33a1c28958.png)

**Comment by vasumahesh1** [comment]
nvm just saw you said the file was there. Might be a rebuild issue. You can also first run a simple node program to check if the win32 one is running perfectly or not.

we can isolate if the issue is with the npm install or the electron rebuild

**Comment by yomansk8** [comment]
Yeah I've already tried to setup a simple node project and it works like a charm!
That's why I'm think it's really an electron rebuild problem.

**Comment by vasumahesh1** [comment]
try [electron-rebuild](https://github.com/electron/electron-rebuild) pretty sure it does the same thing.

**Comment by yomansk8** [comment]
electron-rebuild doesn't seems to work, here is the logs : 

![image](https://cloud.githubusercontent.com/assets/1978745/20011008/7c8d2a82-a2aa-11e6-9495-26ad57e93ed2.png)

**Comment by vasumahesh1** [comment]
Check permissions maybe? I see an EPERM on nslog "operation not permitted, unlink <address>"

**Comment by yomansk8** [comment]
Permissions seems right. I have full control on the folder.

**Comment by yomansk8** [comment]
I've finally found my problem...
My electron project is transpiled with webpack. I just needed to add `printer` to the external modules so webpack dont try to built it.

**Comment by vasumahesh1** [comment]
Alright, glad it worked out.

**Comment by yomansk8** [comment]
Thank for your help 😉

**Comment by rdpascua** [comment]
@yomansk8 I set my `printer` to externals. Now I have `printer is not defined` error. May I know how you resolve this issue?

**Comment by yomansk8** [comment]
@rdpascua Put it in the external modules in webpack was enough for me.
But for me, this error mean that you dont have properly import Printer module.
Just check you have the following in your js file : 
`import printer from 'printer';` and also check if you dont have a "case" problem (printer insted of Printer, etc...)

**Comment by yomansk8** [comment]
Just mark this as closed, I've forget to do it ;)

**Comment by rdpascua** [comment]
@yomansk8 do you have any node loaders installed? 

I have this

```
  externals: ['printer'],
```
imported the right way

```
  import printer from 'printer'
```

**Comment by yomansk8** [comment]
No I dont have particular loaders installed for this...
It's weird. Are you sure that printer is correctly build ?

**Comment by rdpascua** [comment]
How do I know if its correctly built? what Ive tried is include the node module from a test file and executed it and it works.

what i find odd is when I put thenprinter in externals, webpack doesnt allow me to use the module

Sent from my iPhone

On 9 Nov 2016, at 10:22 PM, Yohann Craumacher <notifications@github.com<mailto:notifications@github.com>> wrote:


No I dont have particular loaders installed for this...
It's weird. Are you sure that printer is correctly build ?

-
