### ISSUE TITLE
Print not working on Windows (Image Printing)

### ISSUE THREAD

**Issue by Canser** [tojocky/node-printer#154]
Hello.

When i try to print an image document, the module sends the job to the queue, so i can see the printing job, but nothing happens after that, just waiting...

I saw a post similar to my problem, tried to print text with type: text option, printer got the job but printed blank page...

Any idea?

Thank you.

(Edit: It's not blank, text printed but most of it out of borders)

**Comment by happilymarrieddad** [comment]
I am experiencing the same problem

++

**Comment by tojocky** [comment]
Duplicate of https://github.com/tojocky/node-printer/issues/20
