### ISSUE TITLE
Nothing print

### ISSUE THREAD

**Issue by namtn** [tojocky/node-printer#159]
Hi all, i'm using node-printer to print simple text, node-printer get list printers exactly, but when call print function node-printer just send job to printer but nothing happen. I'm using latest node version and window 10.
If i change type from RAW to TEXT, i got exception:
 `TypeError: StartDocPrinterW error: code: 1804, message: The specified datatype is invalid.`

Here my code:
```js
var printer = require('printer')

function print() {
    printer.printDirect({
        data: 'Simple Text',
        printer: 'HP LaserJet Professional P 1102w',
        type: 'RAW',
        docname: 'Test',
        success: function (jobID) {
            console.log('sent to printer with ID: ' + jobID)
        },
        error: function (err) {
            console.log(err)
        }
    })
}
print()
```

Console log:
![untitled](https://cloud.githubusercontent.com/assets/3005899/21706006/39ccc0e0-d3f6-11e6-8ea1-bb7fb8cddc43.png)

Printer jobs:
![untitled1](https://cloud.githubusercontent.com/assets/3005899/21706010/46e2def4-d3f6-11e6-9322-d4ec3393eff7.png)

Thanks all.

**Comment by tojocky** [comment]
Hi,

RAW format is to send direct commands to printer.

What do you see if you run https://github.com/tojocky/node-printer/blob/master/examples/getSupportedFormats.js ?

**Comment by namtn** [comment]
Hi @tojocky ,
Support format as attach image:
![untitled](https://cloud.githubusercontent.com/assets/3005899/21709798/771773a8-d416-11e6-8d5c-fc9d1d37e65b.png)

Thanks!

**Comment by namtn** [comment]
Hi @tojocky ,
After try with some thermal printer, so node-printer can print well. However, I don't know why it can't print on HP LaserJet P1102W printer?

**Comment by abhishek199-dhn** [comment]
Hi @namtn 

Did it work for you with thermal printer.? I had no success with it as the data is not getting passed to the printer. i.e nothing gets printed.

I'm using Two pilots printer (Virtual Printer Driver) [http://www.colorpilot.com/emfprinter_versions.html](url)

Here is the code

`var printer = require("printer")
printer.printDirect(
     {
        data:"Data to print", 
        printer: 'Two Pilots Demo Printer',
        type: 'RAW',
        success:function(jobId){
		      console.log("Sent to printer with ID: "+jobId);
	    },
        error:function(err){console.log(err);}
});`

Thanks!

**Comment by abhishek199-dhn** [comment]
I got it working..:)

Thanks!!

**Comment by arielpires** [comment]
@abhishek199-dhn, Im having the same problem, how do you get this to work?

**Comment by abhishek199-dhn** [comment]
I have used [node-thermal-printer](https://www.npmjs.com/package/node-thermal-printer) npm module to get the formatted data for thermal printer and use that data as an input.

Here is the code

```javascript
import printer from "printer";
import nodeThermalPrinter from "node-thermal-printer";

nodeThermalPrinter.init({
      type: 'epson',
      interface: 'COM3',
      width: 120,
      characterSet: 'USA',
      removeSpecialCharacters: false, 
      replaceSpecialCharacters: true
});
   
nodeThermalPrinter.alignCenter();
nodeThermalPrinter.newLine();
nodeThermalPrinter.println("********DUMMY DATA**********");

printer.printDirect({
      data: nodeThermalPrinter.getText(),
      type: "RAW",
      success: function (jobId) {
          console.log("SUCCESS", jobId)
      },
      error: function (err) {
           console.log("ERROR", err)   
      }
});
   
```

**Comment by JefferyHus** [comment]
@abhishek199-dhn Thanks for your solution it works :)

**Comment by EmanueleFeola** [comment]
So the  node-thermal-printer  library worked with an HP printer too?
