### ISSUE TITLE
Successful electron-rebuild but windows A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by rcollette** [tojocky/node-printer#164]
Using electron 1.4.15 or electron 1.5.0
I install printer with `npm install printer --save`
I install electron-rebuild with `npm install electron-rebuild --save-dev`
I created an npm script `"rebuild": "electron-rebuild -f -w app"`
I run `npm rebuild` (output  here ->[rebuild.txt](https://github.com/tojocky/node-printer/files/753634/rebuild.txt) )

Everything rebuilds but when trying to use  such as `printer.getDefaultPrinterName()`, through either the main process or a renderer window I get
```
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\code\pb\elec\node_modules\printer\build\Release\node_printer.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\code\pb\elec\node_modules\printer\lib\printer.js:10:22)
    at Module._compile (module.js:571:32)
```

**Comment by tojocky** [comment]
I think you forgot to specify version

**Comment by rcollette** [comment]
electron-rebuild finds the electron version used in your project if I have 1.5 loaded it uses that.  If I have 1.4.15 loaded it will use that.    If you are speaking of something else, please let me know how I should be referring to it.

**Comment by bevinhex** [comment]
How did you solved the problem? I'm having the same issue here.

**Comment by rcollette** [comment]
I wasn't able to resolve this.   We are probably going to not go further with this because there doesn't appear to be support for tray selection on Windows.

**Comment by bevinhex** [comment]
I solved it like this:
```
npm --save install printer
cd node_modules/printer
node-gyp rebuild --target=1.4.13 --arch=x64 --dist-url=https://atom.io/download/atom-shell
```
I was using 1.4.13 version electron, hope this helps.
