### ISSUE TITLE
Is there any way to get "out of paper" status/error information?

### ISSUE THREAD

**Issue by taoyuan** [tojocky/node-printer#166]
Is there any way to get "out of paper" status/error information?

**Comment by tojocky** [comment]
`getJob(printerName, jobId)` or `getPrinter(printerName)`

**Comment by julienazerty** [comment]
When i try to get the "out of paper" status/error by this way (getJob(printerName, jobId)) i got TypeError: Error on GetJob. Wrong job id or it was deleted: code: 87, message: Param\ufffdtre incorrect. 

Any idea on how to get this status ?

**Comment by tojocky** [comment]
As I mentioned, `getPrinter`

**Comment by taoyuan** [comment]
@tojocky Thanks a lot. I found the info about `paper state` in `getPrinter` according to your reply.

Here is it:
```json
{
    "name": "HP_5820_local",
    "isDefault": false,
    "options": {
      "copies": "1",
      "device-uri": "dnssd://HP%20DeskJet%205820%20series%20%5B7AABDC%5D._ipp._tcp.local/",
      "finishings": "3",
      "job-hold-until": "no-hold",
      "job-priority": "50",
      "job-sheets": "none,none",
      "marker-change-time": "2017-06-14T04:34:53.000Z",
      "marker-colors": "#00FFFF#FF00FF#FFFF00,#000000",
      "marker-high-levels": "100,100",
      "marker-levels": "-2,-2",
      "marker-low-levels": "0,0",
      "marker-names": "tri-color\\ ink,black\\ ink",
      "marker-types": "ink-cartridge,ink-cartridge",
      "number-up": "1",
      "printer-commands": "none",
      "printer-info": "HP DeskJet 5820 series",
      "printer-is-accepting-jobs": "true",
      "printer-is-shared": "true",
      "printer-location": "",
      "printer-make-and-model": "HP Deskjet 5820 Series, hpcups 3.16.11",
      "printer-state": "3",
      "printer-state-change-time": "2017-06-14T04:44:28.000Z",
      "printer-state-reasons": "media-empty-warning,media-empty-error,media-needed", // It is here
      "printer-type": "4108",
      "printer-uri-supported": "ipp://localhost:631/printers/HP_5820_local"
    },
    "status": "IDLE",
    "jobs": []
  }
```

`[printer] -> options -> printer-state-reasons` shows the state of paper, marker, toner and so on.

The meaning of the values of `printer-state-reasons` is [here](https://www.cups.org/doc/api-filter.html#MESSAGES).

**Comment by tojocky** [comment]
I'm glad that you found what you're looking for. I tried do not alter the original cups field keys for easy mapping with cups documentation.

**Comment by ronaknewtonsit** [comment]
For some reason our printer always says `"printer-state-reasons":none`. Do you have any idea? We would like to know when the printer is out of paper.

**Comment by Feeh03114** [comment]
Eu estou recebendo assim.
`{ name: 'EPSON TM-T20X', portName: 'TMUSB001', driverName: 'EPSON TM-T(203dpi) Receipt6', printProcessor: 'winprint', datatype: 'RAW', status: [], statusNumber: 0, attributes: [ 'DO-COMPLETE-FIRST', 'LOCAL', 'RAW-ONLY' ], priority: 1, defaultPriority: 0, averagePPM: 0, jobs: [ { id: 28, name: 'EPSON TM-T20X', printerName: 'EPSON TM-T20X', user: 'pc', format: 'RAW', priority: 1, size: 929, status: [], machineName: '\\\\DESKTOP-RS415OU', document: 'node print job', notifyName: 'Totem Homo', printProcessor: 'winprint', driverName: 'EPSON TM-T(203dpi) Receipt6', position: 1, startTime: 0, untilTime: 0, totalPages: 1, time: 0, pagesPrinted: 0 } ] }`

não tenho esse item printer-state-reasons.
