### ISSUE TITLE
GetPrinter not work on virtual printer

### ISSUE THREAD

**Issue by alexandre-le-borgne** [tojocky/node-printer#169]
I'm trying to use getPrinter('ESynaps') but an error occured while this printer is listed in the result of the getPrinters function :

![screenshot_1](https://cloud.githubusercontent.com/assets/10196942/26207711/99fc43be-3be8-11e7-859d-b3f3a7b24161.jpg)

This printer ('ESynaps') is a virtual printer. The function getPrinter(NAME) works well with other printers. I guess the problem depends on the characteristics of the printer. How can I fix it ?

getPrinters result :

> [ { name: 'ESynaps',
>     portName: 'http://localhost:631',
>     driverName: 'Microsoft Print To PDF',
>     printProcessor: 'winprint',
>     datatype: 'RAW',
>     status: [],
>     statusNumber: 0,
>     attributes: [ 'DO-COMPLETE-FIRST', 'LOCAL' ],
>     priority: 1,
>     defaultPriority: 0,
>     averagePPM: 0 },
>   { name: 'Microsoft XPS Document Writer',
>     portName: 'PORTPROMPT:',
>     driverName: 'Microsoft XPS Document Writer v4',
>     printProcessor: 'winprint',
>     datatype: 'RAW',
>     status: [],
>     statusNumber: 0,
>     attributes: [ 'DO-COMPLETE-FIRST', 'LOCAL' ],
>     priority: 1,
>     defaultPriority: 0,
>     averagePPM: 0,
>     startTime: 1380,
>     untilTime: 1380 }]

**Comment by tojocky** [comment]
What command did you use to print?

**Comment by alexandre-le-borgne** [comment]
I do not use a command to print on it. I just retrieve it to find out if it exists or not.

**Comment by alexandre-le-borgne** [comment]
No news ? I get around the problem, but I'm still available if you want clarification.

**Comment by yusef-ho** [comment]
same issue here....
any news?? 
thx
