### ISSUE TITLE
Printer.list() returns empty array

### ISSUE THREAD

**Issue by Shraaa1** [tojocky/node-printer#173]
I have a requirement to fetch the list of printers accessible by my machine. When I use the node-printer module via the below code I get an empty printer list:

_var Printer = require('node-printer');_
_var options = {_
    _media: 'Custom.200x600mm',_
    _n: 3_
_};_

_// Get available printers list_
_console.log(Printer.list());_

I get **[]** as the response.
I do not get any errors both while installing the module or running this code.

**What could be the reason?**
I do have printers set up on my windows machine. **Do I have to configure the printers in a specific manner to get the list?**

**Comment by tojocky** [comment]
You are using different module. this module name is "printer"
