### ISSUE TITLE
Electron Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by kiuKisas** [tojocky/node-printer#181]
Hi, when I try using node-printer in node, it's work well but when I launch it in Electron I got this following error message:
![capture](https://user-images.githubusercontent.com/12698940/29678459-f55e1512-88fe-11e7-8bfe-af655ec2bd1c.PNG)

Did I missed something ? 
Thank's in advance !

**Comment by kiuKisas** [comment]
My bad, sorry

**Comment by theharshin** [comment]
@kiuKisas  How did you solved this issue? I'm getting the same error even after I've rebuilt binary files.

**Comment by AndreTaxiDigital** [comment]
Same error
