### ISSUE TITLE
Error: spawnSync

### ISSUE THREAD

**Issue by aabanaag** [tojocky/node-printer#188]
![image](https://user-images.githubusercontent.com/2245822/30549573-b090cec0-9cc7-11e7-821e-20b403dbb21f.png)
I have that error when trying to call printer().getPrinters(); any clue? Just installed the module using yarn add node-printer

**Comment by AhmedKamal20** [comment]
@aabanaag  How do you solved this ?

**Comment by aabanaag** [comment]
sorry, I didn't solved it. My team decided to pivot approach. :)
