### ISSUE TITLE
Margin options in printFile?

### ISSUE THREAD

**Issue by kevinresol** [tojocky/node-printer#200]
Is it possible to configure the margin size (and possibly other options) when `printFile()`?

**Comment by kevinresol** [comment]
Figured it out:

```js
printer.printFile({
  ...
  options: {
    media: '4x6.Fullbleed' 
  }
})
```

The `media` option varies among printers. 
Run `lpoptions -p <printer-name> -l` to get the list of available values.

Detailed documentation here: https://www.cups.org/doc/options.html#OPTIONS

**Comment by mm-ns** [comment]
This does not seem to be working for me.

is this wrong? 

`options: {
      media: 'Custom.1.77x1.77in' 
    }
`
