### ISSUE TITLE
who can tell me how to change the template of "zebra_printer.js" 

### ISSUE THREAD

**Issue by dogLin** [tojocky/node-printer#210]
In the examples
```
template = "N\nS4\nD15\nq400\nR\nB20,10,0,1,2,30,173,B,\"barcode\"\nP0\n";
```
i use this template print the barcode successfully.
I want know the code's mean when  i want to change the layout and add some text.
So who can tell me what it mean or how to search
thank you very much

**Comment by dogLin** [comment]
@ tojocky 
thank you

**Comment by tojocky** [comment]
Check the printer command language documentation.

**Comment by dogLin** [comment]
I can't find  something command like "N\nS4\nD15\nq400\nR\nB20,10,0,1,2,30,173,B,\"barcode\"\nP0\n"

**Comment by thanikkal** [comment]
If anyone else was wondering (i did), what the template language is: Its EPL
https://www.servopack.de/support/zebra/EPL2_Manual.pdf

You should also be able to use ZPL/ZPL2 for the template if you are dealing with ZEBRA printer.
https://www.zebra.com/content/dam/zebra/manuals/printers/common/programming/zpl-zbi2-pm-en.pdf
