### ISSUE TITLE
nw-gyp rebuild failded

### ISSUE THREAD

**Issue by dingshiwei** [tojocky/node-printer#213]
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.6.3
gyp info using node@8.9.3 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Invalid version number: undefined
gyp ERR! stack     at getNodeDir (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:73:25)
gyp ERR! stack     at PythonFinder.callback (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:45:7)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:493:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild"
gyp ERR! cwd E:\nwjs-sdk-v0.14.7-win-ia32\app\node_modules\printer
gyp ERR! node -v v8.9.3
gyp ERR! nw-gyp -v v3.6.3
gyp ERR! not ok
like this, i use nw.js in v0.14.7

**Comment by CruxCv** [comment]
+1

**Comment by LittlehorseXie** [comment]
you must run the line `nw-gyp rebuild --target=${your nw version}` , it not working on `ne-gyp rebuild`
