### ISSUE TITLE
printer.getPrinters()报错问题

### ISSUE THREAD

**Issue by cycxy** [tojocky/node-printer#216]
const printer = require('printer');
printer.getPrinters();
第一次获取能获取到打印机列表,但是第二次获取的时候就报错了,我在3台电脑上测试了,两台开发电脑可以获取到,一台普通设计用的电脑则无法获取(电脑有一些打印机),直接报错. 但是一直找不到报错的原因,希望有遇到此问题的能给予一些解答!
![qq 20180509093842](https://user-images.githubusercontent.com/8298993/39791170-c019d402-536c-11e8-93fd-ac4fe4053013.png)

**Comment by elhalouiMed** [comment]
same issue 


La première fois que j’ai reçu la liste des imprimantes, mais la deuxième fois, je l’ai testée sur 3 ordinateurs, deux développements étaient disponibles et un ordinateur de conception générale n’a pas pu être obtenu (ordinateur Il y a des imprimantes), signalez directement l'erreur, mais je n'ai pas trouvé la raison de l'erreur, j'espère avoir quelques réponses à ce problème!

**Comment by elhalouiMed** [comment]
Sous Windows, le plugin utilise une libraire qui demande de Windows de retourner la liste des imprimantes installé dans la machine et qu'il sont déjà utilisé par l'utilisateur.

L'erreur retourné est une erreur système ( retourner par Windows ), vu qu'il n'arrive plus à lire correctement le driver d'une imprimante installé et déjà utilisé.

la cause peut être la suppression d'un ou plusieurs fichiers du driver par faute ou par un autre programme installé dans la machine.
