### ISSUE TITLE
configure cutter

### ISSUE THREAD

**Issue by dantero00** [tojocky/node-printer#25]
there is a way to configure the automatic cutter? i use node printer with a mini printer

**Comment by DeepzSandra** [comment]
hi tojocky ,
i have a same problem!! can u pls help me!!!

**Comment by tojocky** [comment]
Hi @DeepzSandra , as I mentioned above, use [Buffer](https://nodejs.org/api/buffer.html) type instead of string.

**Comment by DeepzSandra** [comment]
Thank u so much!!! Jocky.....
