### ISSUE TITLE
undefined symbol: cupsGetDests

### ISSUE THREAD

**Issue by byatis** [tojocky/node-printer#28]
Tried the getPrinters example with linux but the only thing I get when I run it is error undefined symbol: cupsGetDests, do you have any idea what might be causing this?

**Comment by tojocky** [comment]
Thanks a lot for testing. I will add link settings to the condition of OS!=win
```
'link_settings': {
    'libraries': [
        '<!(cups-config --libs)'
    ]
 }
```
