### ISSUE TITLE
How Can I get the default printer name?

### ISSUE THREAD

**Issue by AlexZhouAA** [tojocky/node-printer#33]
I have to get the default printer name in a project and show it as user's default choice.
How can I achieve that using node-printer?

If there do have a way to get that, please tell me how. If not, let getPrinter(printerName) method return the default printer when printerName isn't provided maybe a good idea.

Thanks a lot.

**Comment by jwoertink** [comment]
You could do

```javascript
var mainPrinter,
    Printer = require('printer');
Printer.getPrinters().forEach(function(p) { if(p.isDefault) mainPrinter = p; });
console.log(mainPrinter.name); // Lanier_MP_3500
```

**Comment by AlexZhouAA** [comment]
Thank you for your response. I tried your solution. I couldn't get the default printer name.
I printed out all printers on console using
<code>
   console.log("installed printers:\n"+util.inspect(printer.getPrinters(), {colors:true, depth:10}));
</code>
I found that no printer has the property of isDefault, therefore p.isDefault will be undefined all the time.

**Comment by tojocky** [comment]
This is OS specific. isDefault is true for POSIX only. I still didn't find a method to retrieve the default printer on windows.

Could you please confirm that you are using Windows?

**Comment by AlexZhouAA** [comment]
Yes, you're right. I'm using Windows. Thanks a lot.
