### ISSUE TITLE
Error when using with node-webkit

### ISSUE THREAD

**Issue by jwoertink** [tojocky/node-printer#34]
If I hop into the node console, and just do a simple 
```javascript
var printer = require('printer');
printer.getPrinters();
```
I get the array of all the printers, but when I do the exact same thing inside of [node-webkit](https://github.com/rogerwang/node-webkit) I get this error:

![screen shot 2015-01-06 at 10 48 22 am](https://cloud.githubusercontent.com/assets/2391/5634438/7195e97c-9594-11e4-9961-a746d90f27dd.png)

I'm on OSX 10.9.5. Any ideas on what I should look into?

**Comment by tojocky** [comment]
Rebuild the package with nw-gyp, not with node-gyp

**Comment by jwoertink** [comment]
all I did was `npm install`. Is there a way to specify which one to use?

**Comment by tojocky** [comment]
https://github.com/rogerwang/node-webkit/wiki/Build-native-modules-with-nw-gyp

**Comment by jwoertink** [comment]
hmm.. yeah, that didn't work. I'll see if anyone in the node-webkit community has tried this out. Thanks.
