### ISSUE TITLE
Unable to install printer npm

### ISSUE THREAD

**Issue by ramkishore380** [tojocky/node-printer#37]
While installing i get the following error mentioned in the screen shot
![img-20150114-wa0000](https://cloud.githubusercontent.com/assets/10542162/5752646/293ec5d2-9ca0-11e4-803d-20109cda1ab6.jpg)

**Comment by tojocky** [comment]
Install it from a local clone

**Comment by tojocky** [comment]
Or `npm install printer`

**Comment by ramkishore380** [comment]
Now i get the following error

D:\ProjectITCS\bin\node_modules\printer>node "C:\Program Files (x86)\nodejs\node
_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebu
ild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
VCBUILD : error Message:  [D:\ProjectITCS\bin\node_modules\printer\build\bindin
g.sln]
VCBUILD : System error : -2147154687. [D:\ProjectITCS\bin\node_modules\printer\
build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:
12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\ProjectITCS\bin\node_modules\printer
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! printer@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the printer@0.0.3 install script.
npm ERR! This is most likely a problem with the printer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls printer
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "git+https://gith
ub.com/tojocky/node-printer.git"
npm ERR! cwd D:\ProjectITCS\bin
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by tojocky** [comment]
`VCBUILD : System error : -2147154687`
It is a system error. Did you try to install from VS command Prompt? 
Did you check your logs?
Did you try to find in the internet first what this error mean?
A hint can be:
http://stackoverflow.com/questions/27034592/node-gyp-build-error-for-bcrypt-module-in-windows-nt-6-1-7600-x86

**Comment by ramkishore380** [comment]
Thank you . it's an issue with vc 2008. Installing vc2010 solved it .

**Comment by tojocky** [comment]
Cool
