### ISSUE TITLE
getPrinters does not return all printers

### ISSUE THREAD

**Issue by rsoubeiga** [tojocky/node-printer#40]
HI
I have got some troubles on trying to get printers list,  the method getPrinters does not return all the printers available on my computer.
After some investigations i found that the problem was related to the value of flags parameter passed in EnumPrintersW(flags, .......) see at line 407 in node_printer_win.cc file. 
Indeed when i test getPrinters method on specifying the flags parameter like : 
  DWORD flags = PRINTER_ENUM_LOCAL | PRINTER_ENUM_CONNECTIONS;
It works perfectly.
Could you make this change please ?
Thank you

**Comment by tojocky** [comment]
according by this: https://msdn.microsoft.com/en-us/library/cc244669.aspx
```
PRINTER_ENUM_CONNECTIONS (0x00000004): Enumerate printer connections previously added through RpcAddPerMachineConnection.
```
Indeed, now RPC printers are not enumerated.
Will add this.
