### ISSUE TITLE
getPrinters(); TypeError: wrong job status

### ISSUE THREAD

**Issue by thejae** [tojocky/node-printer#41]
Thanks for this package, am running into some trouble getting the list of printers.

Here is my code
```bash
var printer = require("./node_modules/printer/lib"),
    util = require('util');
console.log("installed printers:\n"+util.inspect(printer.getPrinters(), {colors:true, depth:10}));
```

The error message
```bash
pi@pi-rasp /var/www/nodejs $ node printc

/var/www/nodejs/node_modules/printer/lib/printer.js:57
    var printers = printer_helper.getPrinters();
                                  ^
TypeError: wrong job status:
    at Object.getPrinters (/var/www/nodejs/node_modules/printer/lib/printer.js:57:35)
    at Object.<anonymous> (/var/www/nodejs/printc.js:3:58)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```
Package version: 0.0.5
NodeJS: v0.10.35
CUPS version: 1.5.3
System: Linux pi-rasp 3.18.5+ #748 PREEMPT Wed Feb 4 21:24:41 GMT 2015 armv6l GNU/Linux

**Comment by tojocky** [comment]
Could you please retest with the latest changes (re-install from GIT `npm install git+https://github.com/tojocky/node-printer.git`) and let me know what is the error now. I need to catch the new job status, unsupported by printer module.

Thank you in advance.

**Comment by tojocky** [comment]
I'm closing this issue. Would be nice to have this tested to know what job status is not supported.
