### ISSUE TITLE
printFile

### ISSUE THREAD

**Issue by tojocky** [tojocky/node-printer#43]
Would be nice to add printFile method.
an example is here: https://github.com/shipstation/node-printer

**Comment by pushpak** [comment]
this `printFile` method could be really useful.
Example: convert a webpage to canvas and grab the `base64` from canvas and send it as `Blob` aka file to the printer  (or send pdf/image files directly)

**Comment by tojocky** [comment]
ok, Added. could you please test?

**Comment by tojocky** [comment]
I'm closing this. Please feel free to open issue if something is not working.
