### ISSUE TITLE
POSIX compile error: HTTP_STATUS_CONTINUE not declared

### ISSUE THREAD

**Issue by hilkeheremans** [tojocky/node-printer#47]
Hey there,

The latest commit (0b0b881295106859f2ac43be5cad606a9ae5a45c) / 0.0.5 has introduced a bug where I am unable to compile on (ARM/Raspbian) Nodejs 0.12.0. Node-gyp reports that HTTP_STATUS_CONTINUE is not declared.

0.0.4 on NPM works fine.

Not an advanced Linux/Nodejs guy (yet) so apologies for any oversight on my part.

PS: great work. Your work saved me a lot of time and effort. Thank you for doing this!

**Comment by tojocky** [comment]
What OS? what cups version?

**Comment by tojocky** [comment]
Could you please retest?

Thank you in advance and sorry for this.

**Comment by tojocky** [comment]
I'm closing this because I tested and is working.
