### ISSUE TITLE
Specify size on paper

### ISSUE THREAD

**Issue by snorpey** [tojocky/node-printer#48]
Hi,
Is there a way to specify the output size?
I've tried printing both a PDF file and text. Printing works fine, but for some reason it doesn't fill the whole page. Instead it just fills a small rectangle on the page (see [image](https://cloud.githubusercontent.com/assets/166433/6391567/f440d7b0-bdb7-11e4-9abe-a9170c84ba59.jpg)).

Is this something I need to set in the printer settings in my OS?
(I'm on Mac OSX Yosemite)

**Comment by tojocky** [comment]
Hi, you can do by set default settings.
Feel free to propose patch.
If I will have time I will try to add this.

**Comment by alexeyst** [comment]
Hello!

Thanks for a great node nodule @tojocky!

I really needed this just as well as @snorpey has requested, so I made a quick fix for the printer to support both reading available page sizes and specifying correct page size while printing. 

Please see this pull request: https://github.com/tojocky/node-printer/pull/51

I am actually not a C++ developer, but the fix wasn't too complicated so I decided to go for it; I hope it helps someone else to print, and I hope you can see if some of this code can be used in your module @tojocky.

**Comment by tojocky** [comment]
Thanks for PR.

**Comment by tojocky** [comment]
Closing this because PR from @alexeyst  was integrated
