### ISSUE TITLE
cupsGetDefault2 can return NULL

### ISSUE THREAD

**Issue by lbast2** [tojocky/node-printer#49]
If CUPS server has no default printer defined, cupsGetDefault2 return NULL instead of empty string.

Workaround: in node_printer_posix.cc

MY_NODE_MODULE_CALLBACK(getDefaultPrinterName)
{
    MY_NODE_MODULE_HANDLESCOPE;
    const char * defaultDest = cupsGetDefault2(CUPS_HTTP_DEFAULT);
    if( defaultDest == NULL ) { 
      defaultDest = "";
   }
    MY_NODE_MODULE_RETURN_VALUE(V8_STRING_NEW_UTF8(defaultDest));
}

**Comment by tojocky** [comment]
Do you have error from native library?
If it returns null I think it is fine.

**Comment by lbast2** [comment]
One gets a segmentation fault if NULL.
Tested on OSX 10.9 (CUPS 1.7.2)

Thanks,

Luc Bastiaenssen
Systems manager





	Bibliotheek UAntwerpen
	Stadscampus - S.A.085
	Prinsstraat 9 - 2000 Antwerpen
	luc.bastiaenssen@anet.be 
	T +32 3 265 49 71

**Comment by tojocky** [comment]
Could you please retest?

**Comment by lbast2** [comment]
It works,
Thanks

**Comment by tojocky** [comment]
thanks for quick test. closing this issue
