### ISSUE TITLE
is there a way to read from printer

### ISSUE THREAD

**Issue by iyjian** [tojocky/node-printer#50]
hi,tojocky
   i am new to print on linux, i am not know ,is there a way to read from printer?

**Comment by tojocky** [comment]
what do you mean to read from printer?

**Comment by tojocky** [comment]
closing this because of lack of interest

**Comment by iyjian** [comment]
i use boca printer, and after i send a print command,that printer would send back to me a buffer which indicate it complete that task or the task failed because of lack of paper.  they provide me a c# sample code to do that , it use ReadPrinter api from "winspool.Drv".  i am not know is there a similar way to do that in linux.

**Comment by tojocky** [comment]
Yes, you can do this by using `getJob(printerName, jobId)` if you know job ID, or
`getPrinter(printerName)` will return printer info and all jobs with status.

**Comment by iyjian** [comment]
hi,it is not a job status, it is a buffer returned by printer, could you have a look at this doc? https://msdn.microsoft.com/en-us/library/windows/desktop/dd162895%28v=vs.85%29.aspx  that is a api on windows system, but i want to find a similar api on linux. could you help me?
