### ISSUE TITLE
node-webkit install error

### ISSUE THREAD

**Issue by jmorrisIII** [tojocky/node-printer#52]
Trying to install from node-webkit but failing. Unless I overlooked it I couldn’t find the same problem in other issues. Any ideas?

		npm ERR! Failed to parse json
		npm ERR! Unexpected token /
		npm ERR! File: E:\WebstormProjects\innovation-sales-order-entry\www\package.json
		npm ERR! Failed to parse package.json data.
		npm ERR! package.json must be actual JSON, not just JavaScript.
		npm ERR!
		npm ERR! This is not a bug in npm.
		npm ERR! Tell the package author to fix their package.json file. JSON.parse

		npm ERR! System Windows_NT 6.1.7601
		npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "printer"
		npm ERR! cwd E:\WebstormProjects\innovation-sales-order-entry\www
		npm ERR! node -v v0.10.32
		npm ERR! npm -v 1.4.28
		npm ERR! file E:\WebstormProjects\innovation-sales-order-entry\www\package.json
		npm ERR! code EJSONPARSE
		npm ERR!
		npm ERR! Additional logging details can be found in:
		npm ERR!     E:\WebstormProjects\innovation-sales-order-entry\www\npm-debug.log
		npm ERR! not ok code 0

**Comment by tojocky** [comment]
did you change package.json?

**Comment by jmorrisIII** [comment]
Npm install printer.

**Comment by bwin** [comment]
You have a syntax error in *your* package.json. See the error msg: `File: E:\WebstormProjects\innovation-sales-order-entry\www\package.json`.
Npm always reads your package.json before installing modules.

**Comment by jmorrisIII** [comment]
Thanks @bwin it installed.

**Comment by bwin** [comment]
:+1:

**Comment by tojocky** [comment]
Thanks @bwin

**Comment by bwin** [comment]
Happy to help! :smile: 
Thnx for node-printer.
