### ISSUE TITLE
No getPrinterDriverOptions for windows

### ISSUE THREAD

**Issue by Fenumeor** [tojocky/node-printer#53]
There is no such function defined for windows version, so it does not build!

**Comment by tojocky** [comment]
I know... a patch is coming.

**Comment by tojocky** [comment]
it was resolved by https://github.com/tojocky/node-printer/commit/feb6055b22b6a505ff5b88c7190bdd900ecde2eb

**Comment by Fenumeor** [comment]
There is another issue in same file PrintDirect has REQUIRE_ARGUMENTS(iArgs, 6);
While it should require only 5 (same as posix version)

**Comment by tojocky** [comment]
Indeed. Thanks for spotting this out. Please retest. Unfortunately I don't have a win machine for now.

**Comment by tojocky** [comment]
OK, I installed window 10 on virtual machine and corrected the build.
Closing this issue.

please feel free to reopen if it does nto work for you.

Sorry for this. I'm working on automatic windows build do not repeat this (linux already added).

**Comment by Fenumeor** [comment]
Thanks, sorry, that I did not test.
