### ISSUE TITLE
ESC/POS commands

### ISSUE THREAD

**Issue by jcerdan** [tojocky/node-printer#54]
Hi,

Is it possible to send esc/pos commands to a printer with your module? If yes, could you please provide an example?

best,

**Comment by tojocky** [comment]
I think you could use `RAW` type to send direct to printer. `examples/print_raw.js`. Let me know if this works. Otherwise you have to find the appropiate type format name.

**Comment by jcerdan** [comment]
OK, I have tried but no way... will search hoe the hell this should work.
best,

**Comment by pushpak** [comment]
Here's how to send ESC/POS commands and few links

- [ESC/POS commands list](https://github.com/StadiumRunner/node-escpos/blob/master/lib/commands.js)
- For standard text [link 1](http://webcache.googleusercontent.com/search?q=cache:WUrYIrgddl0J:davidkelley.me/development/work/javascript/web/2013/08/31/javascript-interface-for-esc-pos.html+&cd=4&hl=en&ct=clnk&gl=in)
- For image [link 2](http://nicholas.piasecki.name/blog/2009/12/sending-a-bit-image-to-an-epson-tm-t88iii-receipt-printer-using-c-and-escpos/), should convert to javascript version


example: prints text and feeds 10 lines and cuts the paper.

```
String.prototype.toBytes = function() {
	    var arr = []
	    for (var i=0; i < this.length; i++) {
	        arr.push(this[i].charCodeAt(0))
	    }
	    return arr;
	}

	var printData = "hello world ESC/POS".toBytes().concat([0x01B, 0x64, 10, 0x1d, 0x56, 0x00]);

    printer.printDirect({
    	data: new Buffer(printData)
		, printer:'TM_T88V_S_A_192_168_1_152'
		, type: 'RAW'
		, success:function(jobID){
			console.log("sent to printer with ID: "+jobID);
		}
		, error:function(err){console.log(err);}
	});
```

Note: `0x1d, 0x56, 0x00` is the esc/pos cut command

**Comment by jcerdan** [comment]
Yes! Thanks pushpak. I've looking for this for some time now!
link1 is really useful. 
no need to print images now. but I keep that link in mind!

**Comment by tojocky** [comment]
Thanks @pushpak  for your input. Closing this issue.

**Comment by afaqurk** [comment]
Hey @jcerdan, link 1 from @pushpak 's comment doesn't seem to be working anymore. Can anyone provide me with an updated link?

I'm trying to print to a thermal printer with Node.js and suffering some roadblocks.

**Comment by jcerdan** [comment]
Hi @afaqurk. 
It works fine for me. If you can't see it install npm module node-escpos as it's a file describing commands for printer to cut, align, etc...
This is the module https://github.com/StadiumRunner/node-escpos
The file is located in lib/commands.js
best,

**Comment by afaqurk** [comment]
Sorry, I meant the second link. Specifically, [this one.](http://webcache.googleusercontent.com/search?q=cache:WUrYIrgddl0J:davidkelley.me/development/work/javascript/web/2013/08/31/javascript-interface-for-esc-pos.html+&cd=4&hl=en&ct=clnk&gl=in)

**Comment by pushpak** [comment]
@afaqurk check my updated comment with alternate mirror link

**Comment by afaqurk** [comment]
Thank you!

**Comment by Sangd8** [comment]
Sorry, i tried eveything above, none of it working....
I'm using POS 58 Thermal Printer. I can printer is working, but when i try to send an print command from nodejs use nore-printer. If i set type is TEXT The Printer just print a blank line, any else type, printer says nothing. This is my entire code

var printer = require("printer");

String.prototype.toBytes = function (){
  var arr = [];
  for (var i = 0; i < this.length; i++) {
    arr.push(this[i].charCodeAt(0))
  }
  return arr;
};

var printData = "hello world ESC/POS".toBytes().concat([0x01B, 0x64, 3]);

printer.printDirect({
  data: new Buffer(printData)
  , printer: 'POS58 10.0.0.6'
  , type: 'RAW'
  , success: function (jobID){
    console.log("sent to printer with ID: " + jobID);
  }
  , error: function (err){
    console.log(err);
  }
});

**Comment by tojocky** [comment]
Be care full, Nodejs chars are în UTF8 format. You have to transform imto ASCII I suppose.

**Comment by Sangd8** [comment]
How suppose can i do that? I'm new on nodejs. I'm trying to build a app with NWJS. Thanks

**Comment by Sangd8** [comment]
I tried this
new Buffer(printData, 'ascii')
Still nothing.

**Comment by Sangd8** [comment]
Hey, i found out. I used
new Uint8Array(printData).buffer
It's working now. Thanks :)

**Comment by nohaelsheweikh** [comment]
Hey , Sangd8 , can you please show full code for this if it's working for you ?
i have same problem now , and i used Uint8Array(printData).buffer but it shows error to me 
 Argument 0 must be a string or Buffer
