### ISSUE TITLE
getDefaultPrinterName throwing segmentation fault

### ISSUE THREAD

**Issue by smatejina** [tojocky/node-printer#57]
I am trying to get default printer on mac osx but it's throwing segmentation fault

i am running https://raw.githubusercontent.com/tojocky/node-printer/master/examples/getDefaultPrinterName.js
```
➜  node-printer  node defaultPrinter.js
[1]    51859 segmentation fault  node defaultPrinter.js
```

Any help would be appreciated

**Comment by tojocky** [comment]
With old source code this may happen when the default printer is not defined.
Could you please re-test the latest source code if you have the same issue?

**Comment by smatejina** [comment]
Thanks, I installed directly from github and now segmentation fault is gone.

I still have this issue:
```
➜  node-printer  node defaultPrinter.js
default printer name: is not defined on your computer
```

When I list all printers it says the office_printer is set as default
```
➜  node-printer  node getPrinters.js 
installed printers:
[ { name: 'Office_Printer',
    isDefault: true,
    options: 
     { copies: '1',
```

https://www.dropbox.com/s/su08df3grac8ecd/Screenshot%202015-03-17%2010.33.25.png?dl=0

Any thoughts on this?

**Comment by tojocky** [comment]
The issue seems to be with windows API itself. I noticed this. If you restart the PC and don't change the default printer it works properly. I need to find a way to correct.

**Comment by tojocky** [comment]
I'm closing this issue because it was opened for other reason. Default printer functionality I will think how to do. feel free to propose PR.
