### ISSUE TITLE
"Module did not self-register" in NW.js 0.12.0 64-bit

### ISSUE THREAD

**Issue by jeffbonhag** [tojocky/node-printer#58]
Using a minimal project NW.js 0.12.0 (node-webkit) on Windows 8.1, `require('printer')` fails.

package.json:

    {
      "name": "foo",
      "main": "index.html",
      "dependencies": {
        "printer": "0.1.1"
      }
    }

index.html:

    <!DOCTYPE html>
    <html>
      <head>
        <script>
          var printer = require('printer');
        </script>
      </head>
      <body></body>
    </html>

After running `npm install --msvs_version=2013`, when I run `nw .`, I get the "Module did not self-register" error in the NW.js console.  In contrast, `require('q')` works as expected.

node --version:

    v0.12.0

nw --version:

    nw.js v0.12.0
    io.js v1.2.0
    Chromium 41.0.2272.76
    commit hash: f6c7f79-10b9c03-be948af-459755a-2bdc251-c114bb7

**Comment by tojocky** [comment]
nw v.12.0 uses [iojs](https://iojs.org/en/index.html), but you are trying to build for node v0.12.0. If you want to build for nw you have tu build with [nw-gyp](https://github.com/nwjs/nw-gyp), not with npm of node-gyp

**Comment by jeffbonhag** [comment]
Thanks @tojocky !  I didn't know that was the right thing to do.
