### ISSUE TITLE
Installation fails.

### ISSUE THREAD

**Issue by eloyucu** [tojocky/node-printer#59]
Hello, I am trying to install this module, but there is no way, I get this on the promt when I make npm install:

	gyp: Call to 'cups-config --libs' returned exit status 127. while trying to load binding.gyp
	gyp ERR! configure error
	gyp ERR! stack Error: `gyp` failed with exit code: 1
	gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
	gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
	gyp ERR! System Linux 3.16.0-23-generic
	gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
	gyp ERR! cwd /home/puesto1/app/node_modules/printer
	gyp ERR! node -v v0.10.25
	gyp ERR! node-gyp -v v0.12.2
	gyp ERR! not ok
	npm WARN This failure might be due to the use of legacy binary "node"
	npm WARN For further explanations, please read
	/usr/share/doc/nodejs/README.Debian
	
	npm ERR! printer@0.1.1 install: `node-gyp rebuild`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the printer@0.1.1 install script.
	npm ERR! This is most likely a problem with the printer package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp rebuild
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls printer
	npm ERR! There is likely additional logging output above.
	
	npm ERR! System Linux 3.16.0-23-generic
	npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
	npm ERR! cwd /home/puesto1/app
	npm ERR! node -v v0.10.25
	npm ERR! npm -v 1.4.21
	npm ERR! code ELIFECYCLE
	npm ERR!
	npm ERR! Additional logging details can be found in:
	npm ERR!     /home/puesto1/app/npm-debug.log
	npm ERR! not ok code 0
	
	
I make too "sudo apt-get install nodejs-legacy" that it was a response that I got on stackoverflow, but still doesn´t wrok... any suggestion??

Thank you.

**Comment by tojocky** [comment]
did you try to run `cups-config --libs`?

**Comment by eloyucu** [comment]
Sorry... problem solve!! Finally it wasn´t a issue of this module, I didn´t have installed node-gyp... Here is the post on stackoverflow: http://stackoverflow.com/questions/29122151/error-installing-a-npm-module-printer-on-linux

Thank you.
