### ISSUE TITLE
error:Segmentation fault: 11

### ISSUE THREAD

**Issue by litehot** [tojocky/node-printer#60]
I'm a novice，when i trying to run the example on mac:

var printer = require("printer");

printer.printDirect({data:"print from Node.JS buffer" // or simple String: "some text"
  //, printer:'Foxit Reader PDF Printer' // printer name, if missing then will print to default printer
  , type: 'RAW' // type: RAW, TEXT, PDF, JPEG, .. depends on platform
  , success:function(jobID){
    console.log("sent to printer with ID: "+jobID);
  }
  , error:function(err){console.log(err);}
});

it's take a error like this : Segmentation fault: 11
any suggestions?

**Comment by jimanx2** [comment]
@litehot I got the same error. How did you manage to solve this?

**Comment by jimanx2** [comment]
Never mind, the issue is with my printer driver on OSX. When I tried with other printer it works OK.
