### ISSUE TITLE
Windows not running

### ISSUE THREAD

**Issue by mn1aC** [tojocky/node-printer#62]
Hi,

i'm using nwjs on windows 7. The code runs on mac. But not on windows. What should I do?

**Comment by tojocky** [comment]
Printer module contains native/C++ code. You have to recompile on windows with `nw-gyp rebuild` on windows as you did on mac.

**Comment by mn1aC** [comment]
I've been using nw-gyp rebuild --msvs_version=2013 (with visual studio express 2013 installed)
but I can't make printer work in node-webkit on windows.
require('printer') fails and gives error: Uncaught Error: The specified module could not be found.
C:\Users\USERNAME\Desktop\nw\nw\node_modules\printer\build\Release\node_printer.node

**Comment by mn1aC** [comment]
If I look into the folder: C:\Users\USERNAME\Desktop\nw\nw\node_modules\printer\build\Release\
the file node_printer.node is there...

**Comment by mn1aC** [comment]
And the nw-gyp build was successful (had to install older version of pyton)

**Comment by mn1aC** [comment]
Solved

I had to compile with nw-gyp --arch=ia32 --msvs_version=2013

and had to keep the name of nw.exe default (don't change it!)
https://github.com/agnat/node_mdns/issues/119

**Comment by tojocky** [comment]
This is describes berehttps://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp
