### ISSUE TITLE
Error when installing in windows with "npm install printer --save"

### ISSUE THREAD

**Issue by eblumenfeld** [tojocky/node-printer#65]
I'm receiving this error in my system when installing...

Any pointers?

> printer@0.1.1 install C:\Dropbox\G2Node\node_modules\printer
> node-gyp rebuild

C:\Dropbox\G2Node\node_modules\printer>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1011:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd C:\Dropbox\G2Node\node_modules\printer
gyp ERR! node -v v0.10.34
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! printer@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the printer@0.1.1 install script.
npm ERR! This is most likely a problem with the printer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls printer
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
 "install" "printer" "--save"
npm ERR! cwd C:\Dropbox\G2Node
npm ERR! node -v v0.10.34
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by tojocky** [comment]
Could you please install directly from git? The same error?

**Comment by tojocky** [comment]
What version of python do you have?

**Comment by tojocky** [comment]
Lack of interest

**Comment by eblumenfeld** [comment]
Sorry, I thought I answered both questions, but didn't come through (I'm new in GIT)

I did try to install directly for git, with the same error.

The version of Python I have is 2.7.8 default, Jun 30 2014 MSC v.1500 64 bit (AMD64)

**Comment by eblumenfeld** [comment]
I did post a comment in github but didn't come through... :(

Eduardo Blumenfeld
ed@gotoitsolutions.com
o: 954-892-5878

**Comment by eblumenfeld** [comment]
Hi Ion,

I still can't compile it, tried downloading the zip,
install in node_modules,
move to the folder,
execute
node-gyp config
node-gype build

and I receive:
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  node_printer.cc
  node_printer_win.cc
C:\Users\Eduardo\.node-gyp\0.10.34\deps\v8\include\v8.h(218): warning C4506: no definition for inline function 'v8::Per
sistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\g2ionic\node_modules\node-printer\build\node_printer.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning C4530: C++ exception handler used,
 but unwind semantics are not enabled. Specify /EHsc [C:\g2ionic\node_modules\node-printer\build\node_printer.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xtree(559): warning C4506: no definition for inline func
tion 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\g2ionic\node_modules\node-printer\build\node_printer
.vcxproj]
          with
          [
              T=v8::Object
          ]
LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\g2ionic\node_modules\node-printer\build\node_prin
ter.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Eduardo\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:269:2
3)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\Eduardo\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\g2ionic\node_modules\node-printer
gyp ERR! node -v v0.10.34
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

**Comment by tojocky** [comment]
please try to build with specific Microsoft visual studio by using parameter `node-gyp rebuild --msvs_version=2013`, for Visual studio 2013. Should work also with visual studio 2012 buy using `node-gyp --msvs_version=2012`
Let me know if it works.

**Comment by eblumenfeld** [comment]
Hi Ion,

I could finally make it work, we had to do both the --msvs_version=2012
and the python setup pointing to the python exe rather than just the path:
i.e.: c:\python27\python.exe and not c:\python27

Regards,

Eduardo Blumenfeld
ed@gotoitsolutions.com
o: 954-892-5878

**Comment by sambra22** [comment]
hi Eblumenfeld : 
can you provide me with the steps please how did you got it work please am facing same problem
