### ISSUE TITLE
Cannot install on Windows with node ver 0.12

### ISSUE THREAD

**Issue by metasanjaya** [tojocky/node-printer#67]
Cannot install it on Windows with node ver 0.12

npm log:
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'printer' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink D:\nodejs\\node.exe
5 silly cache add args [ 'printer', null ]
6 verbose cache add spec printer
7 silly cache add parsed spec { raw: 'printer',
7 silly cache add   scope: null,
7 silly cache add   name: 'printer',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed printer@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'printer', range: '*', hasData: false }
12 silly mapToRegistry name printer
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/printer
16 verbose addNameRange registry:https://registry.npmjs.org/printer not in flight; fetching
17 verbose request uri https://registry.npmjs.org/printer
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:16:36 AM
20 verbose request id 1321a93aef516a4d
21 verbose etag "4G6TPIIZPD9IBFNOK3IFWHWIF"
22 http request GET https://registry.npmjs.org/printer
23 http 304 https://registry.npmjs.org/printer
24 silly get cb [ 304,
24 silly get   { date: 'Thu, 02 Apr 2015 20:16:31 GMT',
24 silly get     server: 'Apache',
24 silly get     via: '1.1 varnish',
24 silly get     'last-modified': 'Thu, 02 Apr 2015 20:16:32 GMT',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"4G6TPIIZPD9IBFNOK3IFWHWIF"',
24 silly get     age: '0',
24 silly get     'x-served-by': 'cache-lax1426-LAX',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1428005791.803200,VS0,VE315',
24 silly get     vary: 'Accept',
24 silly get     'content-length': '0',
24 silly get     'keep-alive': 'timeout=10, max=50',
24 silly get     connection: 'Keep-Alive' } ]
25 verbose etag https://registry.npmjs.org/printer from cache
26 verbose get saving printer to C:\Users\Meta\AppData\Roaming\npm-cache\registry.npmjs.org\printer\.cache.json
27 silly addNameRange number 2 { name: 'printer', range: '*', hasData: true }
28 silly addNameRange versions [ 'printer',
28 silly addNameRange   [ '0.0.1',
28 silly addNameRange     '0.0.2',
28 silly addNameRange     '0.0.3',
28 silly addNameRange     '0.0.4',
28 silly addNameRange     '0.0.5',
28 silly addNameRange     '0.0.6',
28 silly addNameRange     '0.1.0',
28 silly addNameRange     '0.1.1' ] ]
29 verbose addNamed printer@0.1.1
30 silly addNamed semver.valid 0.1.1
31 silly addNamed semver.validRange 0.1.1
32 silly cache afterAdd printer@0.1.1
33 verbose afterAdd C:\Users\Meta\AppData\Roaming\npm-cache\printer\0.1.1\package\package.json not in flight; writing
34 verbose afterAdd C:\Users\Meta\AppData\Roaming\npm-cache\printer\0.1.1\package\package.json written
35 silly install resolved [ { name: 'printer',
35 silly install resolved     description: 'Node.js printer bindings',
35 silly install resolved     version: '0.1.1',
35 silly install resolved     homepage: 'http://github.com/tojocky/node-printer',
35 silly install resolved     author:
35 silly install resolved      { name: 'Ion Lupascu',
35 silly install resolved        email: 'ionlupascu@gmail.com',
35 silly install resolved        url: 'http://program-support.co.uk/' },
35 silly install resolved     contributors: [ [Object] ],
35 silly install resolved     repository:
35 silly install resolved      { type: 'git',
35 silly install resolved        url: 'git://github.com/tojocky/node-printer.git' },
35 silly install resolved     devDependencies:
35 silly install resolved      { grunt: '^0.4.5',
35 silly install resolved        'grunt-contrib-copy': '^0.8.0',
35 silly install resolved        'grunt-contrib-jshint': '^0.11.0',
35 silly install resolved        'grunt-node-gyp': 'git://github.com/tojocky/grunt-node-gyp.git',
35 silly install resolved        'grunt-nw-gyp': 'git://github.com/tojocky/grunt-nw-gyp.git',
35 silly install resolved        nodeunit: '*' },
35 silly install resolved     engines: { node: '>= 0.8.0' },
35 silly install resolved     scripts:
35 silly install resolved      { test: 'nodeunit -I lib test/*.test.js',
35 silly install resolved        install: 'node-gyp rebuild' },
35 silly install resolved     licenses: [ [Object] ],
35 silly install resolved     main: './lib/printer',
35 silly install resolved     gypfile: true,
35 silly install resolved     bugs: { url: 'https://github.com/tojocky/node-printer/issues' },
35 silly install resolved     _id: 'printer@0.1.1',
35 silly install resolved     _shasum: 'daeeb16abacd081269d408ba3c3d3281a2e171fc',
35 silly install resolved     _from: 'printer@*',
35 silly install resolved     _npmVersion: '1.4.9',
35 silly install resolved     _npmUser: { name: 'ionlupascu', email: 'ionlupascu@gmail.com' },
35 silly install resolved     maintainers: [ [Object] ],
35 silly install resolved     dist:
35 silly install resolved      { shasum: 'daeeb16abacd081269d408ba3c3d3281a2e171fc',
35 silly install resolved        tarball: 'http://registry.npmjs.org/printer/-/printer-0.1.1.tgz' },
35 silly install resolved     directories: {},
35 silly install resolved     _resolved: 'https://registry.npmjs.org/printer/-/printer-0.1.1.tgz',
35 silly install resolved     readme: 'ERROR: No README data found!' } ]
36 info install printer@0.1.1 into D:\htdocs\ss-management
37 info installOne printer@0.1.1
38 verbose installOne of printer to D:\htdocs\ss-management not in flight; installing
39 verbose lock using C:\Users\Meta\AppData\Roaming\npm-cache\_locks\printer-e44a2ee730dcdb24.lock for D:\htdocs\ss-management\node_modules\printer
40 silly install write writing printer 0.1.1 to D:\htdocs\ss-management\node_modules\printer
41 silly cache addNamed cb printer@0.1.1
42 verbose unbuild node_modules\printer
43 verbose gentlyRm vacuuming D:\htdocs\ss-management\node_modules\printer
44 verbose tar unpack C:\Users\Meta\AppData\Roaming\npm-cache\printer\0.1.1\package.tgz
45 verbose tar unpacking to D:\htdocs\ss-management\node_modules\printer
46 verbose gentlyRm vacuuming D:\htdocs\ss-management\node_modules\printer
47 silly gunzTarPerm modes [ '777', '666' ]
48 silly gunzTarPerm extractEntry package.json
49 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
50 silly gunzTarPerm extractEntry .npmignore
51 silly gunzTarPerm modified mode [ '.npmignore', 420, 438 ]
52 silly gunzTarPerm extractEntry README.md
53 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
54 silly gunzTarPerm extractEntry Gruntfile.js
55 silly gunzTarPerm modified mode [ 'Gruntfile.js', 420, 438 ]
56 silly gunzTarPerm extractEntry printer.js
57 silly gunzTarPerm modified mode [ 'printer.js', 420, 438 ]
58 silly gunzTarPerm extractEntry build/Makefile
59 silly gunzTarPerm modified mode [ 'build/Makefile', 420, 438 ]
60 silly gunzTarPerm extractEntry build/Release/.deps/Release/node_printer.node.d
61 silly gunzTarPerm modified mode [ 'build/Release/.deps/Release/node_printer.node.d', 420, 438 ]
62 silly gunzTarPerm extractEntry build/Release/.deps/Release/obj.target/node_printer/src/node_printer.o.d
63 silly gunzTarPerm modified mode [ 'build/Release/.deps/Release/obj.target/node_printer/src/node_printer.o.d',
63 silly gunzTarPerm   420,
63 silly gunzTarPerm   438 ]
64 silly gunzTarPerm extractEntry build/Release/.deps/Release/obj.target/node_printer/src/node_printer_posix.o.d
65 silly gunzTarPerm modified mode [ 'build/Release/.deps/Release/obj.target/node_printer/src/node_printer_posix.o.d',
65 silly gunzTarPerm   420,
65 silly gunzTarPerm   438 ]
66 silly gunzTarPerm extractEntry build/Release/.deps/Release/obj.target/node_printer.node.d
67 silly gunzTarPerm modified mode [ 'build/Release/.deps/Release/obj.target/node_printer.node.d',
67 silly gunzTarPerm   420,
67 silly gunzTarPerm   438 ]
68 silly gunzTarPerm extractEntry build/Release/linker.lock
69 silly gunzTarPerm modified mode [ 'build/Release/linker.lock', 420, 438 ]
70 silly gunzTarPerm extractEntry build/Release/node_printer.node
71 silly gunzTarPerm modified mode [ 'build/Release/node_printer.node', 493, 511 ]
72 silly gunzTarPerm extractEntry build/Release/obj.target/node_printer/src/node_printer.o
73 silly gunzTarPerm modified mode [ 'build/Release/obj.target/node_printer/src/node_printer.o',
73 silly gunzTarPerm   420,
73 silly gunzTarPerm   438 ]
74 silly gunzTarPerm extractEntry build/Release/obj.target/node_printer/src/node_printer_posix.o
75 silly gunzTarPerm modified mode [ 'build/Release/obj.target/node_printer/src/node_printer_posix.o',
75 silly gunzTarPerm   420,
75 silly gunzTarPerm   438 ]
76 silly gunzTarPerm extractEntry build/Release/obj.target/node_printer.node
77 silly gunzTarPerm modified mode [ 'build/Release/obj.target/node_printer.node', 493, 511 ]
78 silly gunzTarPerm extractEntry build/binding.Makefile
79 silly gunzTarPerm modified mode [ 'build/binding.Makefile', 420, 438 ]
80 silly gunzTarPerm extractEntry build/config.gypi
81 silly gunzTarPerm modified mode [ 'build/config.gypi', 420, 438 ]
82 silly gunzTarPerm extractEntry build/node_printer.target.mk
83 silly gunzTarPerm modified mode [ 'build/node_printer.target.mk', 420, 438 ]
84 silly gunzTarPerm extractEntry ChangeLog
85 silly gunzTarPerm modified mode [ 'ChangeLog', 420, 438 ]
86 silly gunzTarPerm extractEntry lib/index.js
87 silly gunzTarPerm modified mode [ 'lib/index.js', 420, 438 ]
88 silly gunzTarPerm extractEntry lib/printer.js
89 silly gunzTarPerm modified mode [ 'lib/printer.js', 420, 438 ]
90 silly gunzTarPerm extractEntry src/macros.hh
91 silly gunzTarPerm modified mode [ 'src/macros.hh', 420, 438 ]
92 silly gunzTarPerm extractEntry src/node_printer.cc
93 silly gunzTarPerm modified mode [ 'src/node_printer.cc', 420, 438 ]
94 silly gunzTarPerm extractEntry src/node_printer.hpp
95 silly gunzTarPerm modified mode [ 'src/node_printer.hpp', 420, 438 ]
96 silly gunzTarPerm extractEntry src/node_printer_posix.cc
97 silly gunzTarPerm modified mode [ 'src/node_printer_posix.cc', 420, 438 ]
98 silly gunzTarPerm extractEntry src/node_printer_win.cc
99 silly gunzTarPerm modified mode [ 'src/node_printer_win.cc', 420, 438 ]
100 silly gunzTarPerm extractEntry tools/getSourceFiles.py
101 silly gunzTarPerm modified mode [ 'tools/getSourceFiles.py', 420, 438 ]
102 silly gunzTarPerm extractEntry binding.gyp
103 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
104 silly gunzTarPerm extractEntry examples/cancelJob.js
105 silly gunzTarPerm modified mode [ 'examples/cancelJob.js', 420, 438 ]
106 silly gunzTarPerm extractEntry examples/example_zebra_printer.js
107 silly gunzTarPerm modified mode [ 'examples/example_zebra_printer.js', 420, 438 ]
108 silly gunzTarPerm extractEntry examples/getDefaultPrinterName.js
109 silly gunzTarPerm modified mode [ 'examples/getDefaultPrinterName.js', 420, 438 ]
110 silly gunzTarPerm extractEntry examples/getPrinters.js
111 silly gunzTarPerm modified mode [ 'examples/getPrinters.js', 420, 438 ]
112 silly gunzTarPerm extractEntry examples/getSupportedFormats.js
113 silly gunzTarPerm modified mode [ 'examples/getSupportedFormats.js', 420, 438 ]
114 silly gunzTarPerm extractEntry examples/getSupportedJobCommands.js
115 silly gunzTarPerm modified mode [ 'examples/getSupportedJobCommands.js', 420, 438 ]
116 silly gunzTarPerm extractEntry examples/print_raw.js
117 silly gunzTarPerm modified mode [ 'examples/print_raw.js', 420, 438 ]
118 info preinstall printer@0.1.1
119 silly install resolved []
120 verbose about to build D:\htdocs\ss-management\node_modules\printer
121 info build D:\htdocs\ss-management\node_modules\printer
122 verbose linkStuff [ false, false, false, 'D:\\htdocs\\ss-management\\node_modules' ]
123 info linkStuff printer@0.1.1
124 verbose linkBins printer@0.1.1
125 verbose linkMans printer@0.1.1
126 verbose rebuildBundles printer@0.1.1
127 info install printer@0.1.1
128 verbose unsafe-perm in lifecycle true
129 info printer@0.1.1 Failed to exec install script
130 verbose unlock done using C:\Users\Meta\AppData\Roaming\npm-cache\_locks\printer-e44a2ee730dcdb24.lock for D:\htdocs\ss-management\node_modules\printer
131 verbose stack Error: printer@0.1.1 install: `node-gyp rebuild`
131 verbose stack Exit status 1
131 verbose stack     at EventEmitter.<anonymous> (D:\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
131 verbose stack     at EventEmitter.emit (events.js:110:17)
131 verbose stack     at ChildProcess.<anonymous> (D:\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
131 verbose stack     at ChildProcess.emit (events.js:110:17)
131 verbose stack     at maybeClose (child_process.js:1008:16)
131 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
132 verbose pkgid printer@0.1.1
133 verbose cwd D:\htdocs\ss-management
134 error Windows_NT 6.1.7601
135 error argv "D:\\nodejs\\\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "printer"
136 error node v0.12.0
137 error npm  v2.5.1
138 error code ELIFECYCLE
139 error printer@0.1.1 install: `node-gyp rebuild`
139 error Exit status 1
140 error Failed at the printer@0.1.1 install script 'node-gyp rebuild'.
140 error This is most likely a problem with the printer package,
140 error not with npm itself.
140 error Tell the author that this fails on your system:
140 error     node-gyp rebuild
140 error You can get their info via:
140 error     npm owner ls printer
140 error There is likely additional logging output above.
141 verbose exit [ 1, true ]
142 verbose unbuild node_modules\printer
143 info preuninstall printer@0.1.1
144 info uninstall printer@0.1.1
145 verbose unbuild rmStuff printer@0.1.1 from D:\htdocs\ss-management\node_modules
146 info postuninstall printer@0.1.1
147 verbose gentlyRm vacuuming D:\htdocs\ss-management\node_modules\printer
148 silly gentlyRm purging D:\htdocs\ss-management\node_modules\printer
149 silly gentlyRm removing D:\htdocs\ss-management\node_modules
150 silly gentlyRm finished vacuuming up to D:\htdocs\ss-management

**Comment by tojocky** [comment]
For node-webkit you have to rebuild with nw-gyp, not with node-gyp called by npm.
 try to install direct from git:
* `npm install git+https://github.com/tojocky/node-printer.git`
* `cd node_modules\printer`
* `nw-gyp rebuild`

But for this you need [python 2.7](https://www.python.org/download/releases/2.7/), msvs 2012 or [2013](https://www.visualstudio.com/en-us/products/visual-studio-express-vs.aspx) dor desktop and [nw-gyp](https://github.com/nwjs/nw-gyp) node package installed global.

**Comment by metasanjaya** [comment]
I have built it with nw-gyp, now it has error

Uncaught Error: %1 is not a valid Win32 application.
D:\htdocs\ss-management\node_modules\printer\build\Release\node_printer.node

**Comment by tojocky** [comment]
what arch do you use?
Please check the already closed issue #66

**Comment by metasanjaya** [comment]
My Windows is x64, but I want to compile for x86
I think nw-gyp rebuild --arch=ia32 is the answer
Thank you very much
