### ISSUE TITLE
node-printer occasionally crashes node.

### ISSUE THREAD

**Issue by blowsie** [tojocky/node-printer#68]
When using this code
```
  printer.printDirect(
          {
            data   : 'Hello World',
            type   : 'RAW',
            success: function(jobID) {
              console.log("sent to printer with ID: " + jobID);
            },
            error  : function(err) {
              console.error(err);
            }
          }
      );
```

Occasionally it will succeed, and respond with `sent to printer with ID: 119`

But it seems around 50% of the time it fails, and node prints this `Process finished with exit code -1073740940 (0xC0000374)`

My environment is as follows;
```
Windows 8.1

node -v
v0.10.37

npm -v
1.4.28
```

Any ideas why this is happening ? I'm trying to catch an error, but no luck yet, the rror seems to occur inside node_printer.node

**Comment by tojocky** [comment]
did you try the latest version from GIT?

**Comment by blowsie** [comment]
I took the latest NPM version, I can try the GIT version

**Comment by tojocky** [comment]
thanks for testing. let me know the results.

**Comment by wahono77** [comment]
I got crash too on Windows 8.1 using node-webkit. After call getPrinters, sometimes app close without error message.

I got this from crash dump file : 


Dump Summary
------------
Dump File:	1675ca8b-cc2d-4b96-bd98-a5a26555fa2c.dmp : C:\Users\sri wahono\AppData\Local\Temp\1675ca8b-cc2d-4b96-bd98-a5a26555fa2c.dmp
Last Write Time:	02/05/2015 20:25:31
Process Name:	nw.exe : C:\Program Files\AcosysV5\nw.exe
Process Architecture:	x64
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Not Present

System Information
------------------
OS Version:	6.3.9600
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
nw.exe	C:\Program Files\AcosysV5\nw.exe	0.0.0.0
ntdll.dll	C:\Windows\System32\ntdll.dll	6.3.9600.17736
kernel32.dll	C:\Windows\System32\kernel32.dll	6.3.9600.17415
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	6.3.9600.17415
gdi32.dll	C:\Windows\System32\gdi32.dll	6.3.9600.17415
winmm.dll	C:\Windows\System32\winmm.dll	6.3.9600.17415
ws2_32.dll	C:\Windows\System32\ws2_32.dll	6.3.9600.17415
advapi32.dll	C:\Windows\System32\advapi32.dll	6.3.9600.17415
IPHLPAPI.DLL	C:\Windows\System32\IPHLPAPI.DLL	6.3.9600.17415
psapi.dll	C:\Windows\System32\psapi.dll	6.3.9600.17415
comctl32.dll	C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9600.17415_none_6240486fecbd8abb\comctl32.dll	6.10.9600.17415
secur32.dll	C:\Windows\System32\secur32.dll	6.3.9600.17415
crypt32.dll	C:\Windows\System32\crypt32.dll	6.3.9600.17475
imm32.dll	C:\Windows\System32\imm32.dll	6.3.9600.17415
oleacc.dll	C:\Windows\System32\oleacc.dll	7.2.9600.17415
version.dll	C:\Windows\System32\version.dll	6.3.9600.17415
usp10.dll	C:\Windows\System32\usp10.dll	6.3.9600.17415
shlwapi.dll	C:\Windows\System32\shlwapi.dll	6.3.9600.17415
winspool.drv	C:\Windows\System32\winspool.drv	6.3.9600.17415
comdlg32.dll	C:\Windows\System32\comdlg32.dll	6.3.9600.17415
ole32.dll	C:\Windows\System32\ole32.dll	6.3.9600.17415
oleaut32.dll	C:\Windows\System32\oleaut32.dll	6.3.9600.17560
userenv.dll	C:\Windows\System32\userenv.dll	6.3.9600.17415
urlmon.dll	C:\Windows\System32\urlmon.dll	11.0.9600.17728
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	6.3.9600.17415
winhttp.dll	C:\Windows\System32\winhttp.dll	6.3.9600.17415
dhcpcsvc.dll	C:\Windows\System32\dhcpcsvc.dll	6.3.9600.17415
wtsapi32.dll	C:\Windows\System32\wtsapi32.dll	6.3.9600.17415
user32.dll	C:\Windows\System32\user32.dll	6.3.9600.17415
WINMMBASE.dll	C:\Windows\System32\WINMMBASE.dll	6.3.9600.17415
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.9600.17415
nsi.dll	C:\Windows\System32\nsi.dll	6.3.9600.17415
sechost.dll	C:\Windows\System32\sechost.dll	6.3.9600.17734
winnsi.dll	C:\Windows\System32\winnsi.dll	6.3.9600.17415
msasn1.dll	C:\Windows\System32\msasn1.dll	6.3.9600.17415
msctf.dll	C:\Windows\System32\msctf.dll	6.3.9600.17706
combase.dll	C:\Windows\System32\combase.dll	6.3.9600.17415
shell32.dll	C:\Windows\System32\shell32.dll	6.3.9600.17680
profapi.dll	C:\Windows\System32\profapi.dll	6.3.9600.17415
iertutil.dll	C:\Windows\System32\iertutil.dll	11.0.9600.17728
wininet.dll	C:\Windows\System32\wininet.dll	11.0.9600.17728
cfgmgr32.dll	C:\Windows\System32\cfgmgr32.dll	6.3.9600.17415
devobj.dll	C:\Windows\System32\devobj.dll	6.3.9600.17415
CRYPTBASE.DLL	C:\Windows\System32\CRYPTBASE.DLL	6.3.9600.17415
SHCore.dll	C:\Windows\System32\SHCore.dll	6.3.9600.17666
bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	6.3.9600.17415
sspicli.dll	C:\Windows\System32\sspicli.dll	6.3.9600.17415
dbghelp.dll	C:\Windows\System32\dbghelp.dll	6.3.9600.17415
kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	6.3.9600.17415
uxtheme.dll	C:\Windows\System32\uxtheme.dll	6.3.9600.17415
tiptsf.dll	C:\Program Files\Common Files\microsoft shared\ink\tiptsf.dll	6.3.9600.17415
DWrite.dll	C:\Windows\System32\DWrite.dll	6.3.9600.17415
dwmapi.dll	C:\Windows\System32\dwmapi.dll	6.3.9600.17415
nlaapi.dll	C:\Windows\System32\nlaapi.dll	6.3.9600.17415
dhcpcsvc6.DLL	C:\Windows\System32\dhcpcsvc6.DLL	6.3.9600.17415
AudioSes.dll	C:\Windows\System32\AudioSes.dll	6.3.9600.17415
powrprof.dll	C:\Windows\System32\powrprof.dll	6.3.9600.17415
MMDevAPI.dll	C:\Windows\System32\MMDevAPI.dll	6.3.9600.17415
clbcatq.dll	C:\Windows\System32\clbcatq.dll	2001.12.10530.17415
setupapi.dll	C:\Windows\System32\setupapi.dll	6.3.9600.17415
wintrust.dll	C:\Windows\System32\wintrust.dll	6.3.9600.17415
mswsock.dll	C:\Windows\System32\mswsock.dll	6.3.9600.17415
winsta.dll	C:\Windows\System32\winsta.dll	6.3.9600.17415
cryptsp.dll	C:\Windows\System32\cryptsp.dll	6.3.9600.17415
rsaenh.dll	C:\Windows\System32\rsaenh.dll	6.3.9600.17415
bcrypt.dll	C:\Windows\System32\bcrypt.dll	6.3.9600.17415
mscms.dll	C:\Windows\System32\mscms.dll	6.3.9600.17415
rasadhlp.dll	C:\Windows\System32\rasadhlp.dll	6.3.9600.17415
dnsapi.dll	C:\Windows\System32\dnsapi.dll	6.3.9600.17415
mdnsNSP.dll	C:\Program Files\Bonjour\mdnsNSP.dll	3.0.0.10
FWPUCLNT.DLL	C:\Windows\System32\FWPUCLNT.DLL	6.3.9600.17415
propsys.dll	C:\Windows\System32\propsys.dll	7.0.9600.17415
ntmarta.dll	C:\Windows\System32\ntmarta.dll	6.3.9600.17415
IDStore.dll	C:\Windows\System32\IDStore.dll	6.3.9600.17415
samlib.dll	C:\Windows\System32\samlib.dll	6.3.9600.17415
wlidprov.dll	C:\Windows\System32\wlidprov.dll	6.3.9600.17415
apphelp.dll	C:\Windows\System32\apphelp.dll	6.3.9600.17415
ntshrui.dll	C:\Windows\System32\ntshrui.dll	6.3.9600.17415
TortoiseGitStub.dll	C:\Program Files\TortoiseGit\bin\TortoiseGitStub.dll	1.8.8.0
TortoiseGit.dll	C:\Program Files\TortoiseGit\bin\TortoiseGit.dll	1.8.8.0
libgit2_tgit.dll	C:\Program Files\TortoiseGit\bin\libgit2_tgit.dll	0.20.0.0
gitdll.dll	C:\Program Files\TortoiseGit\bin\gitdll.dll	1.8.8.0
msvcp120.dll	C:\Windows\System32\msvcp120.dll	12.0.21005.1
msvcr120.dll	C:\Windows\System32\msvcr120.dll	12.0.21005.1
zlib1_tgit.dll	C:\Program Files\TortoiseGit\bin\zlib1_tgit.dll	1.2.8.0
srvcli.dll	C:\Windows\System32\srvcli.dll	6.3.9600.17415
cscapi.dll	C:\Windows\System32\cscapi.dll	6.3.9600.17415
netutils.dll	C:\Windows\System32\netutils.dll	6.3.9600.17415
mssprxy.dll	C:\Windows\System32\mssprxy.dll	7.0.9600.17415

I use version : 
- node-printer : 0.1.1
- nwjs : 0.12.1

thanks

**Comment by tojocky** [comment]
Could you please extract callstack from dump?

**Comment by tojocky** [comment]
could you please re-install and retry?
The latest version should resolve this issue. closing this ticket.
