### ISSUE TITLE
install err on windows

### ISSUE THREAD

**Issue by litehot** [tojocky/node-printer#69]
> printer@0.1.1 install C:\Users\Administrator.PC-20130121VJYE\Desktop\chat-webs
ocket-master\node_modules\printer
> node-gyp rebuild

C:\Users\Administrator.PC-20130121VJYE\Desktop\chat-websocket-master\node_module
s\printer>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..
\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 12.00.8168 for 80x86
  Copyright (C) Microsoft Corp 1984-1998. All rights reserved.

  cl ?

CL : Command line warning D4024: unrecognized source file type '?', object fil

e assumed [C:\Users\Administrator.PC-20130121VJYE\Desktop\chat-websocket-master
\node_modules\printer\build\node_printer.vcxproj]
  Microsoft (R) Incremental Linker Version 6.00.8168
  Copyright (C) Microsoft Corp 1992-1998. All rights reserved.

  /out:?.exe
  ?
LINK : fatal error LNK1104: cannot open file "?.exe" [C:\Users\Administrator.P

C-20130121VJYE\Desktop\chat-websocket-master\node_modules\printer\build\node_pr
inter.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator.PC-20130121VJYE\Desktop\chat-websocket-maste
r\node_modules\printer
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! printer@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the printer@0.1.1 install script.
npm ERR! This is most likely a problem with the printer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls printer
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "printer"
npm ERR! cwd C:\Users\Administrator.PC-20130121VJYE\Desktop\chat-websocket-maste
r
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Administrator.PC-20130121VJYE\Desktop\chat-websocket-maste
r\npm-debug.log
npm ERR! not ok code 0
/////////////////////////////////////////////////////////
It's looks like can't find the score file.
"unrecognized source file type '?'"
Any help?

**Comment by tojocky** [comment]
Update your compiler. I would recommend you to install visual studio 2013 desktop express edition and to compile/install with the following parameter `--msvs_version=2013`

**Comment by litehot** [comment]
It's works!
