### ISSUE TITLE
about getDefaultPrinterName @ node_printer_win.cc

### ISSUE THREAD

**Issue by Treeyan** [tojocky/node-printer#71]
When call GetDefaultPrinterW(NULL, &bSize); the windows returned need chars length, not bytes length. so, the below ‘MemValue<uint16_t> bPrinterName(bSize);‘ and ’BOOL res = GetDefaultPrinterW((LPWSTR)(bPrinterName.get()), &bSize); ‘ lead heap corruption.

it can be MemValue<uint16_t> bPrinterName(bSize*sizeof(uint16_t)); and work fine.

**Comment by tojocky** [comment]
indeed, thanks: https://msdn.microsoft.com/en-us/library/windows/desktop/dd144876(v=vs.85).aspx

**Comment by Treeyan** [comment]
u r welcome :)
