### ISSUE TITLE
cups in windows via docker

### ISSUE THREAD

**Issue by masterofdaemon** [tojocky/node-printer#74]
can it connect to cups daemon on some port https://registry.hub.docker.com/u/ticosax/cups-in-docker/ ?
i need printFile(image) in windows

**Comment by tojocky** [comment]
what do you mean by cups in windows? cups are only in posix systems.

**Comment by masterofdaemon** [comment]
https://hub.docker.com/r/ticosax/cups-in-docker/ if you run this on windows it will run on port 6631 or anything you need, you can integrate in with nodejs app https://hub.docker.com/_/node/
