### ISSUE TITLE
Always print on default printer

### ISSUE THREAD

**Issue by scyros** [tojocky/node-printer#77]
I'm trying to print in two different printers from nwjs (node-webkit) v0.12.2.

I've noticed that node-printer always tries to print to system default printer.
I'm developing in Mac OS (10.10.4 64bits)

To print i use:
```
printer.printDirect({
            data: pdf_buffer,
            printerName: printer_name,
            type: 'PDF',
            success: function (job_id) { ... },
            error: function (error) { ... }
})
```

where ```printer_name``` comes from choosing the name of one printer from ```printer.getPrinters()```

What could be happening?

**Comment by tojocky** [comment]
Use "printer" instead of "printerName"
