### ISSUE TITLE
Printing in Windows

### ISSUE THREAD

**Issue by bernex** [tojocky/node-printer#78]
Text printing is OK. Win 8.1 64 bit( io.js 32 bit )
I tried print pdf via node-printer(32 bit) + your pdfium(32 bit)...
but:
start printing
print page 0
error from printer:TypeError: StartDocPrinterW error: code: 1804, message: ������� ����� ��� ������.
finished

And nothing from printer...

pdfium saves good to EMF and PNG and BMP... I have checked...

outputFormat is 'EMF'.

How I can print EMF or PNG result?

Thanks!

**Comment by tojocky** [comment]
depends on the printer. I need to figure out what version of EMF accept printer. feel free to propose patches to pdfium project.
Closing this issue because is more related to pdfium.
