### ISSUE TITLE
Invalid access to memory location.

### ISSUE THREAD

**Issue by alparslanahmed** [tojocky/node-printer#79]
I have remote .js file and that outputs this error when i try to print direct: Invalid access to memory location.

**Comment by tojocky** [comment]
What version of printer package do you use?
If you don't use the latest git version, could you please try with the latest git and let me know if you still have the issue?

**Comment by alparslanahmed** [comment]
I am using version 0.1.1

**Comment by vasumahesh1** [comment]
+1 @alparslanahmed Same issue on a Windows 7 VM

**Comment by tojocky** [comment]
fixed on version 0.2.0
