### ISSUE TITLE
Can't build on windows

### ISSUE THREAD

**Issue by sultan99** [tojocky/node-printer#82]
I can't find the reason of this error:

![image](https://cloud.githubusercontent.com/assets/2598056/9813836/d8ae5ef8-58aa-11e5-84b7-19dae1017be6.png)
``
C:\metrix-checkpoint\node_modules\printer>if not defined npm_config_node_gyp (n
de "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
s\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

  node_printer.cc
  node_printer_win.cc
..\src\node_printer_win.cc(645): error C2039: 'HasIndexedPropertiesInExternalArrayData': is not a member of 'v8::Object' [C:\metrix-checkpoint\node_modules\printer\build\node_printer.vcxproj]
  c:\users\user\.node-gyp\4.0.0\include\node\v8.h(2587): note: see declaration  of 'v8::Object'
..\src\node_printer_win.cc(647): error C2039: 'GetIndexedPropertiesExternalArrayData': is not a member of 'v8::Object' [C:\metrix-checkpoint\node_modules\printer\build\node_printer.vcxproj]
  c:\users\user\.node-gyp\4.0.0\include\node\v8.h(2587): note: see declaration  of 'v8::Object'
..\src\node_printer_win.cc(648): error C2039: 'GetIndexedPropertiesExternalArrayDataLength': is not a member of 'v8::Object' [C:\metrix-checkpoint\node_modules\printer\build\node_printer.vcxproj]
  c:\users\user\.node-gyp\4.0.0\include\node\v8.h(2587): note: see declaration  of 'v8::Object'
``

**Comment by tomardern** [comment]
I'm also getting the same error

**Comment by sultan99** [comment]
I found the problem, I used node.js v4 and there was some problems with node-gyp.
As a solution I have installed the old version of node.js (v 0.12) and it works.

**Comment by tojocky** [comment]
also added in npm the latest version, 0.2.0. Closing this issue
