### ISSUE TITLE
GetIndexedPropertiesExternalArrayData is removed in v8 4.4.63.9

### ISSUE THREAD

**Issue by gitawego** [tojocky/node-printer#84]
after updated to node 4.0.0, module can not be built, because ``GetIndexedPropertiesExternalArrayData`` can not be found. 
all the ``IndexedProperties`` concerned methods are replaced by ``v8:: ArrayBuffer``.

see: [commit 70d1f32](https://github.com/nodejs/node/commit/70d1f32f5605465a1a630a64f6f0d35f96c7709d)

hope it helps

**Comment by vikrantpogula** [comment]
@gitawego i've just made a pull request for the upstream changes to 4.0.0 node.. -> #85 . Its not tested yet but would be great if u can test and see if its working as intended.

**Comment by gitawego** [comment]
just tested. it works. thx a lot. hope it can be merged soon.

**Comment by tojocky** [comment]
added in v0.2.0. Thanks guys!
