### ISSUE TITLE
Job stuck in cups queue when RAW.

### ISSUE THREAD

**Issue by bsommardahl** [tojocky/node-printer#88]
I'm new to printing in linux so forgive my vast ignorance. I have the following code:

```javascript
printer.printDirect({
		data: "Hello World",
		type: 'RAW',
		success: function(jobId){
			console.log("Job " + jobId + " printed.");
		},
		error: function(err){
			console.log(err);
		}
	})
```
I have an Epson TM-U220D (serial) on COM1 (ttyS0) in Ubuntu 14.04. I can print a test page from cups successfully, so I am sure the printer is connected and configured correctly. It is also set as the default printer. When I print direct using type: 'TEXT', the printer prints correctly, but the text is a larger font and I need something smaller so that my receipt text can fit. I believe what I need is to use RAW and use printer commands to (somehow) control the font-size. BUT, when I change the type to RAW, no matter what value I send in for `data`, the printer does nothing, I get the `console.log` from the `success` callback (`Job 35 printed.`) and the job stays in the cups queue (state: "held since Mon 21 Sept....").

Any ideas?

**Comment by tojocky** [comment]
RAW command means you communicate directly by sending commands. You need to find what commands can accept your printer. On linux also you can send PDF type if you wand a different font.

**Comment by Klemen1337** [comment]
I have the same issue. Printer gets stuck when I send RAW type data. If I test it with a simple TEXT type it works perfectly.

**Edit1:** It appears to be connected to **bidirectional** communication with the printer. The printer I am using is Sanei SK1-211/221.

```javascript
printer.printDirect({
  data: "TEST",
  printer: printerName,
  type: 'RAW',
  success: function (jobID) {
    console.log("sent to printer with ID: " + jobID);
  },
  error: function (err) {
    console.log(err);
  }
});
```

```javascript
printer.printDirect({
  data: "TEST",
  printer: printerName,
  type: 'TEXT',
  success: function (jobID) {
    console.log("sent to printer with ID: " + jobID);
  },
  error: function (err) {
    console.log(err);
  }
});
```

**Edit2:** I had to change printer settings to not monitor print-end by each print job. Not its working.

![image](https://github.com/tojocky/node-printer/assets/6691011/943b98e0-a391-449b-8100-2801712280e4)
