### ISSUE TITLE
How to control text size in TEXT mode?

### ISSUE THREAD

**Issue by bsommardahl** [tojocky/node-printer#89]
I need to control the size of printed text on my receipts. I'm new to printing with linux so I'm learning as I go. Please forgive my ignorance. 

I have the following code:

```javascript
printer.printDirect({
		data: "hello world",
		options: {
			cpi: 17,
			lpi: 8
		},
		type: 'TEXT',
		success: function(jobId){
			console.log("Job " + jobId + " printed.");
		}
	})
```
I have tried RAW mode and raised a question in another issue about that. When I use TEXT mode, the printed text size is always larger than I want. The text wraps correctly and all, but it's just too large to fit all the information I want to include. 

I added options for `cpi` and `lpi` because I had hoped it would influence the size of the printed text. But the text remains unchanged in all my tests. Maybe I'm not doing the options correctly. I tried to use option names from the `lp` docs.

I have an Epson TM-U220D (serial) on COM1 (ttyS0) in Ubuntu 14.04.

**Comment by tojocky** [comment]
use PDF type to format font, or use direct command to the printer like POSIX
