### ISSUE TITLE
Crashes with 'std::length_error'

### ISSUE THREAD

**Issue by arathael** [tojocky/node-printer#93]
I'm using node `v4.1.2` with package `v0.2.0`. When trying `printDirect()` with a local PDF file it throws:

``` sh
terminate called after throwing an instance of 'std::length_error'
what():  basic_string::assign
```

I could build on Arch ARMv6 after all. This is a RPi B+.

**Comment by tojocky** [comment]
Could you please paste an example code you used? I hope you used Buffer instead of string type for data.

**Comment by arathael** [comment]
It looks something like this, `filename` is a valid PDF file path and `data.id` is just a hash generated by my script:
```js
printer.printDirect({
  data: fs.readFileSync(filename),
  docname: data.id,
  printer: printerName,
  type: 'PDF',
  success: function(jobID) {
    fs.unlinkSync(filename);
  },
  error: function(err) {
    // Some handling
  }
});
```

Where do I change the buffer type?
