### ISSUE TITLE
Buffer printing broken

### ISSUE THREAD

**Issue by vikrantpogula** [tojocky/node-printer#95]
Hey @gitawego @tojocky ... have you guys tested the lasted version against OSX?

Trying to print a PDF / raw buffer seems to just be stuck at `incoming`

attaching screenshot..
<img width="517" alt="screen shot 2015-10-21 at 5 26 03 pm" src="https://cloud.githubusercontent.com/assets/2432643/10635830/368eb99a-7819-11e5-90fb-6eabbca12043.png">

i think the culprit is the code to access arraybuffer itself 

```
v8::ArrayBuffer::Contents data_contents(arg0.As<v8::ArrayBuffer>()->GetContents());
data.assign(static_cast<char*>(data_contents.Data()), data_contents.ByteLength());
```

Could you check ?

**Comment by vikrantpogula** [comment]
Text printing is working fine.

**Comment by tojocky** [comment]
Interesting, could you please retest without last PR?

**Comment by gitawego** [comment]
I use buffer printing to send data to zebra. it works in linux and mac with nodejs 4.x

**Comment by vikrantpogula** [comment]
@tojocky `node-printer-0.2.0` and `nodejs-4.2.1`

@gitawego could you send a sample of your code you use to print from buffer/pdf file !

**Comment by vikrantpogula** [comment]
i have just created this repo... could any of u check against it.. -> https://github.com/vikrantpogula/node-printer-test

- running `node index.js` works fine - `printFile` -> not available on windows
- running `node readfile.js` doesn't work - `printDirect` -> uses file buffer

i use this on windows so option 1 is not really possible... option 2 does as described in the screenshot above (incoming...)

**Comment by gitawego** [comment]
have you tried define: ``type: 'RAW',`` in ``printDirect`` option ?

**Comment by vikrantpogula** [comment]
@gitawego yes, even RAW gets stuck at incoming ....

**Comment by tojocky** [comment]
I confirm this is a bug. a patch and a new release is expected soon.
Thanks for open this issue.

**Comment by tojocky** [comment]
Could you please retest with v0.2.1? it should be OK because I tested locally.
If it is working for you, please close this issue.

**Comment by tojocky** [comment]
@vikrantpogula, still waiting your test.

**Comment by vikrantpogula** [comment]
@tojocky Thank you ! having a look right now

**Comment by vikrantpogula** [comment]
@tojocky Seems fixed, thank you !  I'm going ahead and closing this issue

**Comment by tojocky** [comment]
Thanks for testing.
